fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign from Acoustic Campaign.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Unique identifier for the report associated with the email campaign execution.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific sent email associated with this recipient event.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the email campaign containing this mailing, used to group related mailings.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific content variant or template used in the email sent to the recipient.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred, recorded in the API user's configured timezone.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Category of recipient interaction (e.g., Sent, Open, Click, Bounce, Unsubscribe, Opt-out).

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the email recipient (e.g., To, CC, BCC) as configured in Acoustic Campaign.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body content received by the contact (e.g., HTML, Plain Text).

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking identifier within the email.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient, captured for clickthrough or clickstream events.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Explanation for why the recipient was excluded from receiving the email (e.g., bounce, unsubscribe, opt-out).


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date partition for ETL processing, aligned with Airflow execution date and overlapping with event_timestamp.
