fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received or interacted with the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier for grouping and aggregating campaign performance metrics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing sent to recipients

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the marketing campaign associated with this email activity

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific content variant or version used in the email

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred, recorded in the API user's configured time zone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email engagement event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact recipient (e.g., seed, test, or production recipient)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body the contact received (e.g., HTML, plain text, or multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label or name for the clicked link or clickstream tracking element

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link that was clicked through or tracked via clickstream

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the contact was excluded from receiving the email (e.g., bounced, unsubscribed, spam complaint)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL partition date representing when the data was processed, aligning with the event_timestamp date range
