# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact in Acoustic Campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Report identifier for the email campaign export

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email message

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the email marketing campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Unique identifier for the email content version

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred in user timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (open, click, bounce, etc.)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the email recipient

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Email format type received by the contact (HTML, text, etc.)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: Name assigned to the clicked link or clickstream

- mode: NULLABLE
  name: url
  type: STRING
  description: URL of the clicked link in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the contact was excluded from the mailing


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
