fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign from Acoustic

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier associated with the campaign mailing

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email send/mailing within Acoustic Campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier linking the event to its parent campaign in Acoustic Campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific content variant or version sent to the recipient

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred in the API user's configured timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email engagement event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type in Acoustic Campaign (e.g., seed, regular)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body sent to the recipient (e.g., HTML, text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking element

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL associated with clickthrough or clickstream events

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason code explaining why the contact was suppressed from receiving emails


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL partition date representing Airflow execution date, aligned with event_timestamp
