fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient associated with the email event in Acoustic Campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used for tracking and grouping email campaign analytics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email message that was sent to the recipient

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the marketing campaign to which this email event belongs

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred, recorded in the API user's configured timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Classification of the email interaction event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact recipient (e.g., test, seed, regular subscriber)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body that was delivered to the recipient (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the tracked link or clickstream element within the email

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient (for click-through or clickstream events)

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the email was not delivered or the contact was excluded (e.g., bounced, unsubscribed, opted-out)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date representing when the data was ingested, aligned with Airflow execution date
