fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact or recipient associated with the email event in Acoustic Campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used by Acoustic Campaign for grouping and tracking email metrics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email send or mailing instance in Acoustic Campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the marketing campaign associated with this email event

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred, displayed in the API user's configured timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., seed, test, or production contact) in Acoustic Campaign

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body delivered to the recipient (e.g., HTML, text, or multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label or name for the clicked link or clickstream tracking identifier

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink that was clicked or tracked in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the recipient was suppressed from receiving emails (e.g., bounced, unsubscribed, complaint)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date when the data was ingested, used for partitioning and incremental loads
