fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received or interacted with the email campaign.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Report identifier associated with the email campaign metrics and analytics.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific sent email mailing associated with this recipient event.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Campaign identifier linking this recipient event to its parent marketing campaign.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Content identifier for the specific email template or message version sent to the recipient.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the recipient event occurred, recorded in the API user's configured time zone.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of recipient interaction event (e.g., sent, opened, clicked, bounced, unsubscribed).

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type in the Acoustic Campaign system.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the contact (e.g., HTML, plain text, multipart).

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name assigned to the tracked link or clickstream element within the email.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink that was clicked by the recipient in a clickthrough or clickstream event.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was suppressed from receiving emails (e.g., bounced, unsubscribed, opted out).


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date partition field representing the Airflow execution date, used for data organization and filtering.
