fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient associated with the email event

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Report identifier for grouping events (currently null in source data)

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific sent email message associated with this event

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the email marketing campaign that triggered this event

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred, in the API user's configured time zone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (e.g., sent, delivered, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact type to whom Acoustic Campaign delivered the email

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format type of the email body that the recipient received (e.g., HTML, plain text)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name or label for the clicked link or clickstream within the email

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked in a clickthrough or clickstream event

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was suppressed from receiving emails (e.g., bounced, unsubscribed, opted out)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL partition date representing Airflow's execution date, corresponding to the event_timestamp date
