fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient who received the email from Acoustic Campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used for tracking and aggregating email campaign metrics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing sent to the recipient

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier linking the email event to a specific marketing campaign in Acoustic

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred in the API user's timezone (e.g., sent, opened, clicked)

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email engagement event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type in Acoustic Campaign (e.g., regular, seed, test)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the contact (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name or label assigned to the clicked link or clickstream for tracking purposes

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the recipient's email was suppressed or blocked from delivery (e.g., unsubscribed, bounced, opt-out)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Airflow ETL execution date used for data partitioning, corresponds to the event_timestamp date
