fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Report identifier used for tracking and aggregating campaign metrics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific sent email mailing

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Campaign identifier linking events to their parent marketing campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content variant sent to the recipient

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp of when the email event occurred in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email engagement event (e.g., sent, opened, clicked, bounced)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient type who received the campaign email

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body delivered to the recipient (HTML, text, or multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking element

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink clicked by the recipient

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was excluded from receiving the email (e.g., unsubscribed, bounced)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date partition field representing when data was loaded into BigQuery
