fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient in Acoustic Campaign system who received or interacted with the email.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Unique identifier for the report associated with this email event in Acoustic Campaign.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email mailing in Acoustic Campaign.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the email campaign in Acoustic Campaign.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Unique identifier for the email content template or creative used in the mailing.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred, recorded in the API user's timezone.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email event (e.g., sent, delivered, opened, clicked, bounced, unsubscribed, suppressed).

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., normal, seed, test) indicating their role in the email campaign.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Email body format received by the contact (e.g., HTML, plain text, multipart).

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name assigned to the clicked link or clickstream for tracking purposes.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link clicked by the recipient, capturing clickthrough destinations.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the email was suppressed or recipient was excluded (e.g., opt-out, bounce, complaint, unsubscribe).


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Partition date for ETL processing, aligned with the date component of event_timestamp for data organization.
