fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Identifier linking to the specific report generated for this recipient event

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the email mailing sent to the recipient

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier for the Acoustic Campaign associated with the mailing

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp of the recipient event in the API user's time zone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., contact, seed, test)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Email body format received by the contact (HTML, plain text, or multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name for the clicked link or clickstream identifier

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link clicked by the recipient

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason the contact was suppressed from receiving the email (e.g., unsubscribed, bounced)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
