# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received or interacted with the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Acoustic report identifier associated with the email event

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing that was sent

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the marketing campaign in Acoustic

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Unique identifier for the email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact recipient in the Acoustic Campaign system

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body content received by the contact (e.g., HTML, plain text)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream in the email

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link clicked in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the contact was excluded from receiving the email


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
