fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact in Acoustic Campaign system

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Identifier for the Acoustic Campaign report associated with this event

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email message in Acoustic Campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the Acoustic Campaign associated with the email event

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content template or version used

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (e.g., sent, opened, clicked, bounced)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact recipient in Acoustic Campaign

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body delivered to the contact (e.g., HTML, text)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name assigned to the clicked link or clickstream

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL for clickthrough or clickstream events

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was suppressed from receiving emails


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date when the data was ingested into BigQuery via Airflow pipeline
