fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received or interacted with the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Identifier for the associated email campaign report in Acoustic

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific sent email message in the campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier linking the event to its parent email campaign in Acoustic

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template version sent to the recipient

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred in the API user's timezone (opens, clicks, bounces, etc.)

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (Sent, Open, Click, Bounce, Unsubscribe, etc.)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type in Acoustic Campaign

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body the recipient received (HTML, Text, or Multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name assigned to the clicked link or clickstream for tracking purposes

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link clicked by the recipient in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the recipient was suppressed from receiving the email (bounce, unsubscribe, opt-out, etc.)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Airflow execution date for ETL processing; corresponds to the date within event_timestamp field
