fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier for tracking and analytics purposes

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing that was sent

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Campaign identifier linking this event to a specific marketing campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Exact date and time when the email event occurred in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., subscriber, test contact, seed list)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Email format received by the contact (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name or label assigned to the clicked link or clickstream

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the link clicked in the email for clickthrough tracking

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was suppressed from receiving emails (e.g., bounced, unsubscribed, invalid)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date indicating when the data was imported into BigQuery
