fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient associated with the email event in Acoustic Campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used for tracking and organizing event data exports

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email message that triggered this event

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier linking this event to a specific marketing campaign in Acoustic Campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content template or creative asset used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the email event occurred, recorded in the API user's configured timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Classification of the contact event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Category of the email recipient (e.g., primary recipient, test recipient, seed list)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Email format type received by the contact (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking element within the email

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient (for clickthrough and clickstream events)

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Explanation for why the contact was excluded from receiving the email (e.g., unsubscribed, bounced, invalid email)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date partition used by Airflow, should align with the date component of event_timestamp
