fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used for tracking and analytics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email message in the campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier linking this event to a specific marketing campaign

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content template or variant used

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the event occurred in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of recipient interaction (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact receiving the email (e.g., normal recipient, test recipient)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the contact (e.g., HTML, text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking identifier

- mode: NULLABLE
  name: url
  type: STRING
  description: Complete URL of the hyperlink that was clicked in the email

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason the contact was excluded from receiving emails (e.g., bounced, opted out, invalid address)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Partition date for ETL processing, aligned with the event_timestamp field
