fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date field representing a specific calendar day
- name: user_id_sha256
  type: STRING
  mode: NULLABLE
  description: Unique identifier for a user, client, customer, or account
- name: service
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
  description: ISO country code or country name identifier
- name: seen_in_tier1_country
  type: BOOLEAN
  mode: NULLABLE
  description: ISO country code or country name identifier
- name: registered
  type: BOOLEAN
  mode: NULLABLE
- name: user_agent_device_count
  type: INTEGER
  mode: NULLABLE
  description: Unique identifier for a user, client, customer, or account
