fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date when the data was submitted
- name: user_id_sha256
  type: STRING
  mode: NULLABLE
  description: String value
- name: service
  type: STRING
  mode: NULLABLE
  description: String value
- name: country
  type: STRING
  mode: NULLABLE
  description: ISO country code
- name: seen_in_tier1_country
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean flag or indicator
- name: registered
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean flag or indicator
- name: user_agent_device_count
  type: INTEGER
  mode: NULLABLE
  description: Number of devices associated with the user, per service, per day. Estimated
    from the number of unique user agent strings.
