fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: country_code
  type: STRING
  mode: NULLABLE
  description: Code of the country in which the activity took place, as 
    determined by the IP geolocation. Unknown or NULL values are normally stored
    as '??'.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: Version string of the Firefox browser.
- name: browser_name
  type: STRING
  mode: NULLABLE
  description: Name of the browser application.
- name: search_engine
  type: STRING
  mode: NULLABLE
  description: Search engine used for the search interaction.
- name: search_access_point
  type: STRING
  mode: NULLABLE
  description: Location where the search was initiated from.
- name: default_search_engine
  type: STRING
  mode: NULLABLE
  description: Default search engine configured in the browser.
- name: default_private_search_engine
  type: STRING
  mode: NULLABLE
  description: Default search engine configured for private browsing mode.
- name: pocket_story_position
  type: INTEGER
  mode: NULLABLE
  description: Position of the Pocket story in the newtab page layout.
- name: newtab_open_source
  type: STRING
  mode: NULLABLE
  description: Source from which the new tab was opened.
- name: pocket_is_signed_in
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the user is signed into their Pocket account.
- name: pocket_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether Pocket recommendations are enabled on the new tab page.
- name: pocket_sponsored_stories_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket stories are enabled.
- name: topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether topsites section is enabled on the new tab page.
- name: newtab_homepage_category
  type: STRING
  mode: NULLABLE
  description: Category classification for homepage configuration.
- name: newtab_newtab_category
  type: STRING
  mode: NULLABLE
  description: Category classification for new tab page configuration.
- name: topsites_rows
  type: INTEGER
  mode: NULLABLE
  description: Number of rows of topsites displayed on the new tab page.
- name: is_new_profile
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the profile was newly created.
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: Classification of users based on their browsing activity. E.g., 
    infrequent, casual, regular.
- name: client_count
  type: INTEGER
  mode: NULLABLE
  description: Number of distinct clients with interactions.
- name: legacy_telemetry_client_count
  type: INTEGER
  mode: NULLABLE
  description: Number of distinct clients using legacy telemetry system.
- name: newtab_interactions_visits
  type: INTEGER
  mode: NULLABLE
  description: Number of distinct new tab visit sessions.
- name: topsite_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on topsite tiles.
- name: sponsored_topsite_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored topsite tiles.
- name: organic_topsite_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic topsite tiles.
- name: topsite_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of topsite tiles.
- name: sponsored_topsite_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored topsite tiles.
- name: organic_topsite_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic topsite tiles.
- name: topsite_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of topsite tiles.
- name: sponsored_topsite_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored topsite tiles.
- name: organic_topsite_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic topsite tiles.
- name: searches
  type: INTEGER
  mode: NULLABLE
  description: Total number of search queries performed.
- name: tagged_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on search ads with attribution tags.
- name: tagged_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of search ads with attribution tags.
- name: follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on ads from follow-on search pages.
- name: follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of ads on follow-on search pages.
- name: tagged_follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on tagged ads from follow-on search pages.
- name: tagged_follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of tagged ads on follow-on search pages.
- name: pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of Pocket story recommendations.
- name: sponsored_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored Pocket stories.
- name: organic_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic Pocket stories.
- name: pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on Pocket story recommendations.
- name: sponsored_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored Pocket stories.
- name: organic_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic Pocket stories.
- name: pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Total saves of Pocket stories to user account.
- name: sponsored_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of sponsored Pocket stories.
- name: organic_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of organic Pocket stories.
- name: os
  type: STRING
  mode: NULLABLE
  description: Operating system name.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Operating system version string.
- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether search functionality is enabled on the new tab page.
