fields:
- name: uid
  type: STRING
  mode: NULLABLE
  description: Unique identifier for a user, client, customer, or account
- name: normalizedEmail
  type: STRING
  mode: NULLABLE
  description: Email address
- name: email
  type: STRING
  mode: NULLABLE
  description: Email address
- name: emailVerified
  type: BOOLEAN
  mode: NULLABLE
  description: Email address
- name: verifierVersion
  type: INTEGER
  mode: NULLABLE
  description: Version number or build identifier
- name: verifierSetAt
  type: TIMESTAMP
  mode: NULLABLE
- name: createdAt
  type: TIMESTAMP
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
  description: Language or locale code
- name: lockedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: profileChangedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: keysChangedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: ecosystemAnonId
  type: STRING
  mode: NULLABLE
  description: Device type, platform, operating system, or browser identifier
- name: disabledAt
  type: TIMESTAMP
  mode: NULLABLE
- name: metricsOptOutAt
  type: TIMESTAMP
  mode: NULLABLE
