fields:
- mode: NULLABLE
  name: app_version
  type: STRING
  description: User-visible browser version string (e.g., '1.0.3') extracted from unified_metrics
- mode: NULLABLE
  name: attributed
  type: BOOLEAN
  description: Boolean flag indicating whether the user has any attribution data (true if attribution_medium or attribution_source exists)
- mode: NULLABLE
  name: attribution_medium
  type: STRING
  description: Marketing attribution medium identifier from unified_metrics tracking campaign channels
- mode: NULLABLE
  name: attribution_source
  type: STRING
  description: Marketing attribution source identifier from unified_metrics tracking traffic origins
- mode: NULLABLE
  name: country
  type: STRING
  description: ISO country code where activity occurred, determined by IP geolocation from unified_metrics
- mode: NULLABLE
  name: device_model
  type: STRING
  description: Device model identifier from unified_metrics, particularly relevant for mobile devices
- mode: NULLABLE
  name: first_seen_year
  type: INTEGER
  description: Year when the user profile was first observed, extracted from first_seen_date in unified_metrics
- mode: NULLABLE
  name: is_default_browser
  type: BOOLEAN
  description: Boolean indicating if the browser is set as the system default on the client device
- mode: NULLABLE
  name: app_name
  type: STRING
  description: Normalized application name (e.g., 'Firefox Desktop', 'Fenix') from unified_metrics
- mode: NULLABLE
  name: channel
  type: STRING
  description: Normalized distribution channel (e.g., 'release', 'beta', 'nightly') from unified_metrics
- mode: NULLABLE
  name: os
  type: STRING
  description: Normalized operating system name (e.g., 'Windows', 'macOS', 'Android') from unified_metrics
- mode: NULLABLE
  name: os_version
  type: STRING
  description: Full normalized operating system version string from unified_metrics
- mode: NULLABLE
  name: os_version_major
  type: INTEGER
  description: Major version number of the operating system (e.g., 100 from '100.9.11')
- mode: NULLABLE
  name: os_version_minor
  type: INTEGER
  description: Minor version number of the operating system (e.g., 9 from '100.9.11')
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date when telemetry data was received by the server, used for partitioning
- mode: NULLABLE
  name: dau
  type: INTEGER
  description: Daily Active Users - count of distinct clients active on submission_date (days_since_seen = 0)
- mode: NULLABLE
  name: wau
  type: INTEGER
  description: Weekly Active Users - count of distinct clients active within the last 7 days (days_since_seen < 7)
- mode: NULLABLE
  name: mau
  type: INTEGER
  description: Monthly Active Users - count of all distinct clients in the 28-day activity window
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: Count of distinct clients where submission_date equals first_seen_date, indicating new user profiles
- mode: NULLABLE
  name: ad_clicks
  type: INTEGER
  description: Total number of ad clicks aggregated from unified_metrics for the given segment
- mode: NULLABLE
  name: organic_search_count
  type: INTEGER
  description: Total count of organic (non-sponsored) search queries performed by users
- mode: NULLABLE
  name: search_count
  type: INTEGER
  description: Total count of all search queries including both organic and sponsored searches
- mode: NULLABLE
  name: search_with_ads
  type: INTEGER
  description: Total count of search queries that displayed advertisements
- mode: NULLABLE
  name: uri_count
  type: INTEGER
  description: Total count of URI/page loads across all users in the segment
- mode: NULLABLE
  name: active_hours
  type: FLOAT
  description: Total sum of active browsing hours across all users, calculated from active_hours_sum in unified_metrics
- description: Qualified Daily Active Users for Desktop - Firefox Desktop clients with days_since_seen=0, active_hours>0, and uri_count>0
  mode: NULLABLE
  name: qdau_desktop
  type: INTEGER
