fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: legacy_telemetry_client_id
  type: STRING
  mode: NULLABLE
  description: Client ID from legacy Firefox telemetry system for 
    cross-referencing
- name: newtab_visit_count
  type: INTEGER
  mode: NULLABLE
  description: Total number of new tab page visits by the client on the 
    submission date
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Version number of the normalized operating system
- name: country_code
  type: STRING
  mode: NULLABLE
  description: Code of the country in which the activity took place, as 
    determined by the IP geolocation. Unknown or NULL values are normally stored
    as '??'.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: Version string of the Firefox browser
- name: browser_name
  type: STRING
  mode: NULLABLE
  description: Name of the browser application
- name: default_search_engine
  type: STRING
  mode: NULLABLE
  description: Search engine set as default in Firefox
- name: default_private_search_engine
  type: STRING
  mode: NULLABLE
  description: Search engine set as default for private browsing mode
- name: pocket_is_signed_in
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user is signed into their Pocket account
- name: pocket_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether Pocket recommendations are enabled on the new tab
- name: pocket_sponsored_stories_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket stories are enabled
- name: topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether top sites feature is enabled on the new tab
- name: topsites_sponsored_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored top sites tiles are enabled
- name: newtab_weather_widget_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether weather widget is enabled on the new tab page
- name: newtab_homepage_category
  type: STRING
  mode: NULLABLE
  description: Configuration category for the homepage new tab
- name: newtab_newtab_category
  type: STRING
  mode: NULLABLE
  description: Configuration category for the new tab page
- name: topsites_rows
  type: INTEGER
  mode: NULLABLE
  description: Number of rows configured for displaying top sites
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier or slug
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Branch or variant assigned to the client in the experiment
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Type classification of the experiment
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique identifier for the client's enrollment in the 
          experiment
      description: Additional experiment metadata
    description: Experiment configuration details
  description: Active experiments and their configurations for the client
- name: visits_with_non_impression_engagement
  type: INTEGER
  mode: NULLABLE
  description: Count of new tab visits where user engaged beyond viewing 
    impressions
- name: visits_with_non_search_engagement
  type: INTEGER
  mode: NULLABLE
  description: Count of new tab visits with engagement excluding search actions
- name: visits_with_non_default_ui
  type: INTEGER
  mode: NULLABLE
  description: Count of new tab visits where UI was customized from default 
    settings
- name: is_new_profile
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the client profile was newly created
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: Classification of users based on their browsing activity. E.g., 
    infrequent, casual, regular.
- name: searches
  type: INTEGER
  mode: NULLABLE
  description: Total number of searches performed from the new tab page
- name: tagged_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on search ads attributed to Mozilla via revenue tags
- name: tagged_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of search ads attributed to Mozilla via revenue tags
- name: follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on ads from follow-on search result pages
- name: follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of ads on follow-on search result pages
- name: tagged_follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Tagged ad clicks from follow-on searches attributed to Mozilla
- name: tagged_follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Tagged ad impressions from follow-on searches attributed to 
    Mozilla
- name: topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on top sites tiles
- name: sponsored_topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored top sites tiles
- name: organic_topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic (non-sponsored) top sites tiles
- name: topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of top sites tiles
- name: sponsored_topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored top sites tiles
- name: organic_topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic top sites tiles
- name: topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of top sites tiles by user
- name: sponsored_topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored top sites tiles
- name: organic_topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic top sites tiles
- name: pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of Pocket recommendations
- name: sponsored_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored Pocket content
- name: organic_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic Pocket recommendations
- name: pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on Pocket recommendations
- name: sponsored_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored Pocket content
- name: organic_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic Pocket recommendations
- name: pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Total saves to Pocket from new tab
- name: sponsored_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of sponsored Pocket content
- name: organic_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of organic Pocket content
- name: wallpaper_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks to change or select new tab wallpaper
- name: wallpaper_clicks_had_previous_wallpaper
  type: INTEGER
  mode: NULLABLE
  description: Wallpaper clicks when user already had a custom wallpaper set
- name: wallpaper_clicks_first_selected_wallpaper
  type: INTEGER
  mode: NULLABLE
  description: Wallpaper clicks representing first-time wallpaper selection
- name: wallpaper_category_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on wallpaper category navigation
- name: wallpaper_highlight_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of wallpaper feature highlights or prompts
- name: wallpaper_highlight_cta_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on wallpaper feature call-to-action prompts
- name: weather_widget_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of the weather widget on new tab
- name: weather_widget_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on the weather widget
- name: weather_widget_load_errors
  type: INTEGER
  mode: NULLABLE
  description: Count of weather widget loading failures
- name: weather_widget_change_display_to_detailed
  type: INTEGER
  mode: NULLABLE
  description: Changes from simple to detailed weather view
- name: weather_widget_change_display_to_simple
  type: INTEGER
  mode: NULLABLE
  description: Changes from detailed to simple weather view
- name: weather_widget_location_selected
  type: INTEGER
  mode: NULLABLE
  description: Location selections or changes in weather widget
- name: visits_with_default_ui
  type: INTEGER
  mode: NULLABLE
  description: Count of new tab visits with default UI configuration
- name: visits_with_default_ui_with_non_impression_engagement
  type: INTEGER
  mode: NULLABLE
  description: Default UI visits with engagement beyond impressions
- name: visits_with_default_ui_with_non_search_engagement
  type: INTEGER
  mode: NULLABLE
  description: Default UI visits with non-search engagement
- name: topic_preferences_set
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has set topic preferences for content 
    personalization
- name: sponsored_pocket_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored Pocket recommendations
- name: organic_pocket_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic Pocket recommendations
- name: pocket_thumbs_up
  type: INTEGER
  mode: NULLABLE
  description: Positive feedback (thumbs up) on Pocket recommendations
- name: pocket_thumbs_down
  type: INTEGER
  mode: NULLABLE
  description: Negative feedback (thumbs down) on Pocket recommendations
- name: pocket_thumb_voting_events
  type: INTEGER
  mode: NULLABLE
  description: Total voting events (thumbs up + thumbs down) on Pocket content
- name: topic_selection_selected_topics_first_time
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user selected topics for the first time
- name: topic_selection_updates
  type: INTEGER
  mode: NULLABLE
  description: Number of times user updated their topic preferences
- name: topic_selection_opened
  type: INTEGER
  mode: NULLABLE
  description: Times the topic selection interface was opened
- name: topic_selection_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Times the topic selection prompt was dismissed
- name: profile_group_id
  type: STRING
  mode: NULLABLE
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: topsites_sponsored_tiles_configured
  type: INTEGER
  mode: NULLABLE
  description: An integer from client configuration that determines how many 
    tiles the client can see. This telemetry released in Fx123 (2024/02/20), so 
    it should only be considered for clients with Fx123+.
- name: non_search_engagement_count
  type: INTEGER
  mode: NULLABLE
  description: Total non-search engagements including clicks, saves, dismissals,
    and interactions
- name: newtab_dismissal_count
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of new tab content elements
- name: list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on list-style Pocket card recommendations
- name: organic_list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic list-style Pocket cards
- name: sponsored_list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored list-style Pocket cards
- name: list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of list-style Pocket cards
- name: organic_list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic list-style Pocket cards
- name: sponsored_list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored list-style Pocket cards
- name: list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Total saves from list-style Pocket cards
- name: organic_list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves from organic list-style Pocket cards
- name: sponsored_list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves from sponsored list-style Pocket cards
- name: list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of list-style Pocket cards
- name: organic_list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic list-style Pocket cards
- name: sponsored_list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored list-style Pocket cards
