fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: legacy_telemetry_client_id
  type: STRING
  mode: NULLABLE
  description: Legacy telemetry client identifier for backward compatibility 
    with older telemetry systems.
- name: newtab_visit_count
  type: INTEGER
  mode: NULLABLE
  description: Total number of new tab page visits by the client on this date.
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Version string of the normalized operating system.
- name: country_code
  type: STRING
  mode: NULLABLE
  description: Code of the country in which the activity took place, as 
    determined by the IP geolocation. Unknown or NULL values are normally stored
    as '??'.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: Version string of the Firefox browser.
- name: browser_name
  type: STRING
  mode: NULLABLE
  description: Name identifier of the browser application.
- name: default_search_engine
  type: STRING
  mode: NULLABLE
  description: Search engine configured as default for regular browsing.
- name: default_private_search_engine
  type: STRING
  mode: NULLABLE
  description: Search engine configured as default for private browsing mode.
- name: pocket_is_signed_in
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the user is signed in to their Pocket account.
- name: pocket_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether Pocket integration is enabled in the new tab page.
- name: pocket_sponsored_stories_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket stories are enabled for display.
- name: topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the top sites section is enabled on the new tab page.
- name: topsites_sponsored_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored top sites tiles are enabled.
- name: newtab_weather_widget_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the weather widget is enabled on the new tab page.
- name: newtab_homepage_category
  type: STRING
  mode: NULLABLE
  description: Configuration setting for homepage display category.
- name: newtab_newtab_category
  type: STRING
  mode: NULLABLE
  description: Configuration setting for new tab page display category.
- name: topsites_rows
  type: INTEGER
  mode: NULLABLE
  description: Number of rows configured for displaying top sites.
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Unique identifier for the experiment.
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Experiment branch assignment for the client.
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Type classification of the experiment.
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique identifier for this client's experiment enrollment.
      description: Additional experiment metadata and configuration.
    description: Experiment configuration details including branch and 
      enrollment information.
  description: Active experiments and their branch assignments for this client.
- name: visits_with_non_impression_engagement
  type: INTEGER
  mode: NULLABLE
  description: Count of visits where user engaged beyond viewing impressions.
- name: visits_with_non_search_engagement
  type: INTEGER
  mode: NULLABLE
  description: Count of visits where user engaged with content other than 
    search.
- name: visits_with_non_default_ui
  type: INTEGER
  mode: NULLABLE
  description: Count of visits with customized or non-default UI configurations.
- name: is_new_profile
  type: BOOLEAN
  mode: NULLABLE
  description: Whether this is a newly created Firefox profile.
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: Classification of users based on their browsing activity. E.g., 
    infrequent, casual, regular.
- name: searches
  type: INTEGER
  mode: NULLABLE
  description: Total number of searches initiated from the new tab page.
- name: tagged_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on tagged search advertisements from new tab searches.
- name: tagged_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of tagged search advertisements from new tab 
    searches.
- name: follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on advertisements in follow-on search result pages.
- name: follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of advertisements in follow-on search result pages.
- name: tagged_follow_on_search_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on tagged advertisements in follow-on search pages.
- name: tagged_follow_on_search_ad_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of tagged advertisements in follow-on search pages.
- name: topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on top site tiles.
- name: sponsored_topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored top site tiles.
- name: organic_topsite_tile_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic (non-sponsored) top site tiles.
- name: topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of top site tiles.
- name: sponsored_topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored top site tiles.
- name: organic_topsite_tile_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic (non-sponsored) top site tiles.
- name: topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of top site tiles by user.
- name: sponsored_topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored top site tiles.
- name: organic_topsite_tile_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic top site tiles.
- name: pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of Pocket content cards.
- name: sponsored_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored Pocket content.
- name: organic_pocket_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic (non-sponsored) Pocket content.
- name: pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on Pocket content cards.
- name: sponsored_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored Pocket content.
- name: organic_pocket_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic Pocket content.
- name: pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Total saves of Pocket content to user's reading list.
- name: sponsored_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of sponsored Pocket content.
- name: organic_pocket_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of organic Pocket content.
- name: wallpaper_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks to change new tab wallpaper.
- name: wallpaper_clicks_had_previous_wallpaper
  type: INTEGER
  mode: NULLABLE
  description: Wallpaper changes when user already had a custom wallpaper.
- name: wallpaper_clicks_first_selected_wallpaper
  type: INTEGER
  mode: NULLABLE
  description: First-time wallpaper selections by user.
- name: wallpaper_category_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on wallpaper category selections.
- name: wallpaper_highlight_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of wallpaper feature highlights.
- name: wallpaper_highlight_cta_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on wallpaper call-to-action highlights.
- name: weather_widget_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of the weather widget.
- name: weather_widget_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on the weather widget.
- name: weather_widget_load_errors
  type: INTEGER
  mode: NULLABLE
  description: Number of errors encountered loading the weather widget.
- name: weather_widget_change_display_to_detailed
  type: INTEGER
  mode: NULLABLE
  description: Changes from simple to detailed weather view.
- name: weather_widget_change_display_to_simple
  type: INTEGER
  mode: NULLABLE
  description: Changes from detailed to simple weather view.
- name: weather_widget_location_selected
  type: INTEGER
  mode: NULLABLE
  description: User selections of weather location.
- name: visits_with_default_ui
  type: INTEGER
  mode: NULLABLE
  description: Count of visits using the default new tab UI configuration.
- name: visits_with_default_ui_with_non_impression_engagement
  type: INTEGER
  mode: NULLABLE
  description: Default UI visits with engagement beyond impressions.
- name: visits_with_default_ui_with_non_search_engagement
  type: INTEGER
  mode: NULLABLE
  description: Default UI visits with non-search related engagement.
- name: topic_preferences_set
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has configured topic preferences for content 
    personalization.
- name: sponsored_pocket_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored Pocket content cards.
- name: organic_pocket_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic Pocket content cards.
- name: pocket_thumbs_up
  type: INTEGER
  mode: NULLABLE
  description: Positive feedback (thumbs up) on Pocket content.
- name: pocket_thumbs_down
  type: INTEGER
  mode: NULLABLE
  description: Negative feedback (thumbs down) on Pocket content.
- name: pocket_thumb_voting_events
  type: INTEGER
  mode: NULLABLE
  description: Total thumb voting events (up or down) on Pocket content.
- name: topic_selection_selected_topics_first_time
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user selected topics for the first time.
- name: topic_selection_updates
  type: INTEGER
  mode: NULLABLE
  description: Number of times user updated their topic selections.
- name: topic_selection_opened
  type: INTEGER
  mode: NULLABLE
  description: Number of times user opened the topic selection interface.
- name: topic_selection_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Number of times user dismissed the topic selection prompt.
- name: profile_group_id
  type: STRING
  mode: NULLABLE
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: topsites_sponsored_tiles_configured
  type: INTEGER
  mode: NULLABLE
  description: An integer from client configuration that determines how many 
    tiles the client can see. This telemetry released in Fx123 (2024/02/20), so 
    it should only be considered for clients with Fx123+.
- name: non_search_engagement_count
  type: INTEGER
  mode: NULLABLE
  description: Total count of all non-search engagement actions including 
    clicks, saves, dismissals, and preference updates.
- name: newtab_dismissal_count
  type: INTEGER
  mode: NULLABLE
  description: Total count of content dismissals across all new tab surfaces.
- name: list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total clicks on Pocket list card format content.
- name: organic_list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on organic Pocket list cards.
- name: sponsored_list_card_clicks
  type: INTEGER
  mode: NULLABLE
  description: Clicks on sponsored Pocket list cards.
- name: list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Total impressions of Pocket list card format.
- name: organic_list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of organic Pocket list cards.
- name: sponsored_list_card_impressions
  type: INTEGER
  mode: NULLABLE
  description: Impressions of sponsored Pocket list cards.
- name: list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Total saves of Pocket list card content.
- name: organic_list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of organic Pocket list cards.
- name: sponsored_list_card_saves
  type: INTEGER
  mode: NULLABLE
  description: Saves of sponsored Pocket list cards.
- name: list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Total dismissals of Pocket list cards.
- name: organic_list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of organic Pocket list cards.
- name: sponsored_list_card_dismissals
  type: INTEGER
  mode: NULLABLE
  description: Dismissals of sponsored Pocket list cards.
