fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date field representing a specific calendar day
- mode: NULLABLE
  name: user_id_sha256
  type: STRING
  description: Unique identifier for a user, client, customer, or account
- mode: NULLABLE
  name: service
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
  description: ISO country code or country name identifier
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: Unique identifier for a user, client, customer, or account
- mode: NULLABLE
  name: days_seen_in_tier1_country_bits
  type: INTEGER
  description: ISO country code or country name identifier
- mode: NULLABLE
  name: days_registered_bits
  type: INTEGER
  description: Date field representing a specific calendar day
- name: user_agent_device_count
  type: INTEGER
  mode: NULLABLE
  description: Unique identifier for a user, client, customer, or account
