fields:
- description: The date when the telemetry ping is received on the server side. Used as the partitioning key for the table.
    Represents the aggregation date for all metrics in this row.
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: A unique identifier (UUID) for the client. Used to aggregate multiple pings from the same client on a given
    day. Core dimension for user-level analysis.
  mode: NULLABLE
  name: client_id
  type: STRING
- description: Total count of content process abnormal aborts across all pings for this client on this day. Extracted from
    subprocess_abnormal_abort keyed histogram with key 'content'. Indicates content process stability issues.
  mode: NULLABLE
  name: aborts_content_sum
  type: INTEGER
- description: Total count of GMP (Gecko Media Plugin) process abnormal aborts across all pings for this client on this day.
    Extracted from subprocess_abnormal_abort keyed histogram with key 'gmplugin'.
  mode: NULLABLE
  name: aborts_gmplugin_sum
  type: INTEGER
- description: Total count of plugin process abnormal aborts across all pings for this client on this day. Extracted from
    subprocess_abnormal_abort keyed histogram with key 'plugin'. Tracks NPAPI plugin stability.
  mode: NULLABLE
  name: aborts_plugin_sum
  type: INTEGER
- description: Average number of active addons across all pings for this client on this day. Calculated using AVG(ARRAY_LENGTH(environment.addons.active_addons)).
    Measures addon usage intensity.
  mode: NULLABLE
  name: active_addons_count_mean
  type: FLOAT
- description: Aggregated array of active addons for this client on this day. Contains addon_id, blocklisted status, user_disabled,
    app_disabled, version, scope, type, foreign_install, has_binary_components, install_day, update_day, signed_state, is_system,
    is_web_extension, and multiprocess_compatible fields. Aggregated using udf.aggregate_active_addons to deduplicate and
    merge addon information across multiple pings.
  fields:
  - description: 'Telemetry metric: active_addons.addon_id. Aggregated from Firefox telemetry pings for this client on this
      day.'
    mode: NULLABLE
    name: addon_id
    type: STRING
  - description: 'Telemetry metric: active_addons.blocklisted. Aggregated from Firefox telemetry pings for this client on
      this day.'
    mode: NULLABLE
    name: blocklisted
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.name. Aggregated from Firefox telemetry pings for this client on this day.'
    mode: NULLABLE
    name: name
    type: STRING
  - description: 'Telemetry metric: active_addons.user_disabled. Aggregated from Firefox telemetry pings for this client on
      this day.'
    mode: NULLABLE
    name: user_disabled
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.app_disabled. Aggregated from Firefox telemetry pings for this client on
      this day.'
    mode: NULLABLE
    name: app_disabled
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.version. Aggregated from Firefox telemetry pings for this client on this
      day.'
    mode: NULLABLE
    name: version
    type: STRING
  - description: 'Telemetry metric: active_addons.scope. Aggregated from Firefox telemetry pings for this client on this day.'
    mode: NULLABLE
    name: scope
    type: INTEGER
  - description: 'Telemetry metric: active_addons.type. Aggregated from Firefox telemetry pings for this client on this day.'
    mode: NULLABLE
    name: type
    type: STRING
  - description: 'Telemetry metric: active_addons.foreign_install. Aggregated from Firefox telemetry pings for this client
      on this day.'
    mode: NULLABLE
    name: foreign_install
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.has_binary_components. Aggregated from Firefox telemetry pings for this
      client on this day.'
    mode: NULLABLE
    name: has_binary_components
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.install_day. Aggregated from Firefox telemetry pings for this client on
      this day.'
    mode: NULLABLE
    name: install_day
    type: INTEGER
  - description: 'Telemetry metric: active_addons.update_day. Aggregated from Firefox telemetry pings for this client on this
      day.'
    mode: NULLABLE
    name: update_day
    type: INTEGER
  - description: 'Telemetry metric: active_addons.signed_state. Aggregated from Firefox telemetry pings for this client on
      this day.'
    mode: NULLABLE
    name: signed_state
    type: INTEGER
  - description: 'Telemetry metric: active_addons.is_system. Aggregated from Firefox telemetry pings for this client on this
      day.'
    mode: NULLABLE
    name: is_system
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.is_web_extension. Aggregated from Firefox telemetry pings for this client
      on this day.'
    mode: NULLABLE
    name: is_web_extension
    type: BOOLEAN
  - description: 'Telemetry metric: active_addons.multiprocess_compatible. Aggregated from Firefox telemetry pings for this
      client on this day.'
    mode: NULLABLE
    name: multiprocess_compatible
    type: BOOLEAN
  mode: REPEATED
  name: active_addons
  type: RECORD
- description: DEPRECATED - Previously stored the branch of the active experiment. This field is now deprecated and set to
    NULL. Use experiments array instead.
  mode: NULLABLE
  name: active_experiment_branch
  type: STRING
- description: DEPRECATED - Previously stored the ID of the active experiment. This field is now deprecated and set to NULL.
    Use experiments array instead.
  mode: NULLABLE
  name: active_experiment_id
  type: STRING
- description: Total active hours for this client on this day. Calculated as SUM(active_ticks / (3600/5)), where active_ticks
    are 5-second intervals of user activity. Represents actual user engagement time.
  mode: NULLABLE
  name: active_hours_sum
  type: FLOAT
- description: Most recent value of the addon compatibility check setting. True if Firefox checks addon compatibility. Retrieved
    from environment.settings.addon_compatibility_check_enabled using mode_last aggregation.
  mode: NULLABLE
  name: addon_compatibility_check_enabled
  type: BOOLEAN
- description: Firefox build ID in YYYYMMDDHHMMSS format. Most recent value across all pings for this client on this day.
    Sourced from application.build_id using mode_last aggregation.
  mode: NULLABLE
  name: app_build_id
  type: STRING
- description: User-visible version string (e.g., '1.0.3') for the browser. Most recent value across all pings. Sourced from
    application.display_version.
  mode: NULLABLE
  name: app_display_version
  type: STRING
- description: Application name (typically 'Firefox'). Most recent value across all pings. Sourced from application.name using
    mode_last aggregation.
  mode: NULLABLE
  name: app_name
  type: STRING
- description: User-visible version string (e.g., '1.0.3') for the browser. Most recent value across all pings. Sourced from
    application.version.
  mode: NULLABLE
  name: app_version
  type: STRING