fields:
- description: The date when the telemetry ping is received on the server side. This is the partitioning key for the table and represents when data was collected, not necessarily when it was generated.
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: A unique identifier (UUID) for the client. This is the primary dimension for aggregation and is stable across browser sessions for a given Firefox installation.
  mode: NULLABLE
  name: client_id
  type: STRING