fields:
- name: id
  type: NUMERIC
  mode: NULLABLE
  description: Unique identifier for the security event record
- name: uid
  type: STRING
  mode: NULLABLE
  description: Account ID in hexadecimal format.
- name: nameId
  type: INTEGER
  mode: NULLABLE
  description: Foreign key reference to the security event name
- name: verified
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates whether the account was verified at the time of the event
- name: ipAddrHmac
  type: STRING
  mode: NULLABLE
  description: ipAddrHmac in hexadecimal format.
- name: createdAt
  type: TIMESTAMP
  mode: NULLABLE
  description: Timestamp when the security event was recorded
- name: tokenVerificationId
  type: STRING
  mode: NULLABLE
  description: tokenVerificationId in hexadecimal format.
- name: ipAddr
  type: STRING
  mode: NULLABLE
  description: IP address from which the security event originated
