fields:

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.

- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: Date when the app store activity occurred, 7 days prior to submission_date.

- mode: NULLABLE
  name: country
  type: STRING
  description: Name of the country in which the activity took place, as determined by the IP geolocation.

- mode: NULLABLE
  name: impressions
  type: INTEGER
  description: Count of unique device impressions for Firefox iOS in the Apple App Store.

- mode: NULLABLE
  name: total_downloads
  type: INTEGER
  description: Total number of Firefox iOS app downloads from the Apple App Store.

- mode: NULLABLE
  name: first_time_downloads
  type: INTEGER
  description: Number of users downloading Firefox iOS for the first time.

- mode: NULLABLE
  name: redownloads
  type: INTEGER
  description: Number of users re-downloading Firefox iOS after previous installation.

- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: Number of new Firefox iOS user profiles created on the first_seen_date.
