fields:

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.

- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: Date when the user was first observed, offset by 7 days from submission_date to align with App Store data availability.

- mode: NULLABLE
  name: country
  type: STRING
  description: Name of the country in which the activity took place, as determined by the IP geolocation.

- mode: NULLABLE
  name: impressions
  type: INTEGER
  description: Count of unique device impressions for Firefox iOS app in the Apple App Store, excluding institutional purchases and web/app referrers.

- mode: NULLABLE
  name: total_downloads
  type: INTEGER
  description: Total count of Firefox iOS app downloads from the Apple App Store, including both first-time downloads and redownloads.

- mode: NULLABLE
  name: first_time_downloads
  type: INTEGER
  description: Count of initial Firefox iOS app downloads from users who have never previously downloaded the app.

- mode: NULLABLE
  name: redownloads
  type: INTEGER
  description: Count of Firefox iOS app downloads from users who previously downloaded the app.

- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: Count of new Firefox iOS release channel profiles created on the first_seen_date.
