fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date when telemetry ping was received on server side; used for 
    partitioning the aggregated metrics by day
- name: first_seen_year
  type: INTEGER
  mode: NULLABLE
  description: Year of user's first ping; enables cohort-based analysis by 
    tracking when users first appeared in the dataset
- name: channel
  type: STRING
  mode: NULLABLE
  description: Firefox distribution channel (e.g., release, beta, nightly); 
    normalized for consistent reporting across user segments
- name: app_name
  type: STRING
  mode: NULLABLE
  description: 'Application identifier (Firefox Desktop); includes distribution_id
    suffix for MozillaOnline distributions and ISP markers for BrowserStack users'
- name: country
  type: STRING
  mode: NULLABLE
  description: ISO country code from IP geolocation where activity occurred; 
    unknown values stored as '??' for privacy-compliant aggregation
- name: city
  type: STRING
  mode: NULLABLE
  description: User-reported city location; provides geographic granularity for 
    urban vs rural user distribution analysis
- name: locale
  type: STRING
  mode: NULLABLE
  description: User interface language and country preferences; indicates 
    localization settings for regional targeting insights
- name: os
  type: STRING
  mode: NULLABLE
  description: Normalized operating system name running Firefox; standardized 
    for cross-platform usage comparison
- name: os_grouped
  type: STRING
  mode: NULLABLE
  description: Operating system category grouping; provides higher-level OS 
    segmentation for simplified trend analysis
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Complete operating system version string; enables 
    version-specific compatibility and performance tracking
- name: os_version_major
  type: INTEGER
  mode: NULLABLE
  description: Major OS version number (first segment); useful for tracking 
    adoption of major OS releases
- name: os_version_minor
  type: INTEGER
  mode: NULLABLE
  description: Minor OS version number (second segment); tracks incremental OS 
    updates and patch levels
- name: os_version_build
  type: STRING
  mode: NULLABLE
  description: OS build identifier string; provides detailed version info for 
    Windows diagnostics
- name: windows_build_number
  type: INTEGER
  mode: NULLABLE
  description: 'Windows-specific build number (e.g., 22000); null for non-Windows
    platforms, enables Windows version tracking'
- name: app_version
  type: STRING
  mode: NULLABLE
  description: User-visible Firefox version string (e.g., '1.0.3'); complete 
    version identifier for release tracking
- name: app_version_major
  type: NUMERIC
  mode: NULLABLE
  description: 'Major Firefox version number; primary version identifier for tracking
    major releases (e.g., 123 from 123.0)'
- name: app_version_minor
  type: NUMERIC
  mode: NULLABLE
  description: 'Minor Firefox version number; tracks point releases within major version
    (e.g., 0 from 123.0)'
- name: app_version_patch_revision
  type: NUMERIC
  mode: NULLABLE
  description: 'Patch and revision level of Firefox version; identifies hotfixes and
    security updates'
- name: app_version_is_major_release
  type: BOOLEAN
  mode: NULLABLE
  description: 'Boolean flag indicating major Firefox release; distinguishes major
    versions from point releases'
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean flag indicating if Firefox is set as default browser; 
    measures browser preference and market position
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Firefox distribution identifier; tracks custom Firefox builds and
    partnership distributions
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: User engagement classification (e.g., infrequent, casual, 
    regular); categorizes users by browsing frequency patterns
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: 'Marketing channel medium (e.g., referral, firefox desktop); tracks
    how users discovered or installed Firefox'
- name: attribution_source
  type: STRING
  mode: NULLABLE
  description: 'Marketing source identifier (e.g., firefox browser, search fox); specific
    campaign or partner source attribution'
- name: daily_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of users who sent pings on submission_date; aggregated from
    baseline_active_users where is_daily_user=true'
- name: weekly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of users who sent pings within 7 days of submission_date; aggregated
    from baseline_active_users where is_weekly_user=true'
- name: monthly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of users who sent pings within 28 days of submission_date; aggregated
    from baseline_active_users where is_monthly_user=true'
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: 'Daily Active Users count based on activity metrics on submission_date;
    aggregated from baseline_active_users where is_dau=true'
- name: wau
  type: INTEGER
  mode: NULLABLE
  description: 'Weekly Active Users count based on activity within 7 days; aggregated
    from baseline_active_users where is_wau=true'
- name: mau
  type: INTEGER
  mode: NULLABLE
  description: 'Monthly Active Users count based on activity within 28 days; aggregated
    from baseline_active_users where is_mau=true'
