fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping was received on the server side. This field is used for day-level table partitioning and is required in all query WHERE clauses for optimal performance. Sourced directly from the baseline_active_users table and serves as the primary temporal dimension for aggregation.
- name: first_seen_year
  type: INTEGER
  mode: NULLABLE
  description: Year extracted from the first_seen_date, representing the year when the user's first telemetry ping was received by Mozilla servers. This dimension enables cohort analysis by allowing segmentation of users based on their acquisition year. Sourced from the baseline_active_users table and useful for tracking user retention and long-term behavior patterns.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized distribution channel of the Firefox application (e.g., release, beta, nightly, esr). This field is one of the three clustering dimensions (along with app_name and country) and is critical for version rollout analysis, comparing stability across channels, and segmenting user populations by release track. Sourced from baseline_active_users.
- name: app_name
  type: STRING
  mode: NULLABLE
  description: Application identifier, typically 'Firefox Desktop'. For clients from MozillaOnline distribution, the distribution_id is appended to differentiate the distribution partner. For BrowserStack clients, the ISP information is appended. This field is one of the three primary clustering dimensions, optimizing queries that filter by application type. Sourced from baseline_active_users.
- name: country
  type: STRING
  mode: NULLABLE
  description: ISO country code indicating the geographic location where the activity occurred, determined by IP geolocation on the server side. Unknown or unresolvable locations are stored as '??'. This field is one of the three primary clustering dimensions, making geographic analysis highly efficient. Essential for regional user distribution analysis, market penetration studies, and compliance reporting. Sourced from baseline_active_users.
- name: city
  type: STRING
  mode: NULLABLE
  description: City name where the client activity occurred, derived from IP geolocation. Provides more granular geographic segmentation than country-level data, useful for urban vs. rural analysis, city-specific campaigns, and detailed geographic distribution studies. May be NULL when city-level geolocation is unavailable. Sourced from baseline_active_users.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Language and regional preferences configured in the user interface, typically in the format 'language-COUNTRY' (e.g., 'en-US', 'fr-FR'). This field enables localization analysis, language preference tracking, and helps identify markets for translation priorities. Different from the OS language and represents the user's explicit preference. Sourced from baseline_active_users.
- name: os
  type: STRING
  mode: NULLABLE
  description: Normalized name of the operating system running on the client device (e.g., Windows, macOS, Linux). Standardized for consistency across different reporting mechanisms. Critical for OS-specific compatibility analysis, feature adoption by platform, and technical support prioritization. Sourced from baseline_active_users.
- name: os_grouped
  type: STRING
  mode: NULLABLE
  description: High-level operating system grouping that aggregates similar OS variants into broader categories (e.g., grouping Windows 10 and Windows 11 under 'Windows'). Useful for simplified platform-level analysis when specific version details are not required. Sourced from baseline_active_users.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Complete operating system version string reported by the client (e.g., '10.0.22000' for Windows, '14.1' for macOS). Provides the full version detail before parsing into major/minor/build components. Essential for identifying OS-specific bugs and compatibility requirements. Sourced from baseline_active_users.
- name: os_version_major
  type: INTEGER
  mode: NULLABLE
  description: Major component of the operating system version number. For example, in version '100.9.11', the major version is 100. This parsed field enables efficient numerical comparison and filtering of OS versions, useful for determining minimum OS requirements and tracking OS upgrade adoption. Sourced from baseline_active_users.
- name: os_version_minor
  type: INTEGER
  mode: NULLABLE
  description: Minor component of the operating system version number. For example, in version '100.9.11', the minor version is 9. Combined with os_version_major, provides granular OS version tracking for compatibility analysis and feature support decisions. Sourced from baseline_active_users.
- name: os_version_build
  type: STRING
  mode: NULLABLE
  description: Operating system build identifier or patch level reported by the client. Provides the most granular level of OS version detail, useful for tracking specific builds associated with security patches or bug fixes. May be NULL for operating systems that don't report build numbers. Sourced from baseline_active_users.
- name: windows_build_number
  type: INTEGER
  mode: NULLABLE
  description: Windows-specific build number (e.g., 22000 for Windows 11 initial release, 19041 for Windows 10 version 2004). Only populated for Windows clients; NULL for all other operating systems. Essential for tracking Windows version adoption and identifying Windows-specific compatibility issues. Sourced from baseline_active_users.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: Complete user-visible version string for the Firefox browser (e.g., '1.0.3', '121.0.1'). This is the version displayed in the About Firefox dialog. Used for tracking version distribution across the user base and identifying the need for update campaigns. Sourced from baseline_active_users.
- name: app_version_major
  type: NUMERIC
  mode: NULLABLE
  description: Major version number of the Firefox application. For example, if the app_version is '123.0.1', the major version is 123. This parsed field is critical for tracking major version rollout progress, adoption rates of new releases, and planning deprecation of older versions. Sourced from baseline_active_users.
- name: app_version_minor
  type: NUMERIC
  mode: NULLABLE
  description: Minor version number of the Firefox application. For example, if the app_version is '123.0.1', the minor version is 0. Combined with major version, enables tracking of point releases and dot-version adoption. Sourced from baseline_active_users.
- name: app_version_patch_revision
  type: NUMERIC
  mode: NULLABLE
  description: Patch or revision number of the Firefox application version. Represents bug fix releases and security patches within a major.minor version. Important for tracking emergency update adoption and patch distribution effectiveness. May be NULL for versions without patch numbers. Sourced from baseline_active_users.
- name: app_version_is_major_release
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean flag indicating whether the current app_version represents a major release (TRUE) or a minor/patch release (FALSE). Major releases typically introduce significant new features and changes. Useful for filtering analysis to focus on major version milestones and understanding adoption patterns of flagship releases. Sourced from baseline_active_users.
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean flag indicating whether Firefox is configured as the default web browser on the client's operating system. TRUE when Firefox is the default browser, FALSE otherwise, NULL when the status cannot be determined. This metric is critical for measuring browser market position, default browser campaigns effectiveness, and user commitment. Sourced from baseline_active_users.
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Distribution identifier associated with the Firefox installation, indicating the source or partner responsible for the distribution (e.g., 'mozilla', 'mozillaonline-', OEM partners). NULL for standard Mozilla distributions. Used for tracking partner distributions, OEM installations, and regional distribution variants. Sourced from baseline_active_users.
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: User classification based on browsing activity patterns and engagement levels (e.g., 'infrequent_user', 'casual_user', 'regular_user', 'heavy_user'). This segmentation is calculated upstream based on days active, pages visited, and session duration. Essential for user engagement analysis, identifying at-risk users, and tailoring retention strategies. Sourced from baseline_active_users.
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: Marketing medium through which the user acquired Firefox (e.g., 'organic', 'referral', 'paidsearch', 'display', 'email'). Part of the attribution model used to measure marketing campaign effectiveness. NULL when attribution data is unavailable. Used for marketing ROI analysis and channel optimization. Sourced from baseline_active_users.
- name: attribution_source
  type: STRING
  mode: NULLABLE
  description: Specific marketing source or campaign that led to Firefox acquisition (e.g., 'google', 'bing', 'facebook', specific campaign names). More granular than attribution_medium. Essential for detailed marketing attribution, comparing campaign performance, and optimizing acquisition spend. NULL when attribution data is unavailable. Sourced from baseline_active_users.
- name: daily_users
  type: INTEGER
  mode: NULLABLE
  description: Count of unique users who submitted at least one baseline ping on the submission_date, regardless of browsing activity. Calculated by aggregating COUNTIF(is_daily_user) from the baseline_active_users table. This metric measures ping submission behavior rather than active engagement. Compare with 'dau' to understand the difference between connected users and actively browsing users.
- name: weekly_users
  type: INTEGER
  mode: NULLABLE
  description: Count of unique users who submitted at least one baseline ping within the 7-day period ending on submission_date. Calculated by aggregating COUNTIF(is_weekly_user) from baseline_active_users. Represents the weekly user base based on ping submission patterns, useful for weekly engagement trends. Compare with 'wau' to differentiate between ping-submitting users and actively browsing users.
- name: monthly_users
  type: INTEGER
  mode: NULLABLE
  description: Count of unique users who submitted at least one baseline ping within the 28-day period ending on submission_date. Calculated by aggregating COUNTIF(is_monthly_user) from baseline_active_users. Represents the monthly user base based on ping submission patterns, the broadest measure of user reach. Compare with 'mau' to understand the difference between monthly reach and monthly active engagement.
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: Daily Active Users - count of unique users with actual browsing activity (page loads, searches, interactions) on the submission_date. Calculated by aggregating COUNTIF(is_dau) from baseline_active_users. This is a stricter metric than 'daily_users' as it requires active engagement beyond just connecting to Mozilla servers. The primary metric for measuring daily user engagement and the foundation for DAU/MAU ratios.
- name: wau
  type: INTEGER
  mode: NULLABLE
  description: Weekly Active Users - count of unique users with actual browsing activity within the 7-day period ending on submission_date. Calculated by aggregating COUNTIF(is_wau) from baseline_active_users. Measures weekly active engagement rather than just ping submission. Used for calculating weekly engagement trends and stickiness ratios. Typically lower than 'weekly_users' due to stricter activity requirements.
- name: mau
  type: INTEGER
  mode: NULLABLE
  description: Monthly Active Users - count of unique users with actual browsing activity within the 28-day period ending on submission_date. Calculated by aggregating COUNTIF(is_mau) from baseline_active_users. The standard metric for measuring monthly active user base, used in DAU/MAU ratio calculations to determine user stickiness and engagement health. Represents users with meaningful browser interaction over the past month, not just those who connected.
