fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: newtab_visit_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for a single newtab visit session
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: country
  type: STRING
  mode: NULLABLE
  description: Name of the country in which the activity took place, as 
    determined by the IP geolocation.
- name: homepage_category
  type: STRING
  mode: NULLABLE
  description: User's configured homepage appearance setting
- name: newtab_category
  type: STRING
  mode: NULLABLE
  description: User's configured newtab page appearance setting
- name: organic_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user enabled organic Pocket stories
- name: sponsored_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user enabled sponsored Pocket stories
- name: sponsored_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user enabled sponsored topsite tiles
- name: organic_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user enabled organic topsite tiles
- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user enabled search functionality on newtab
- name: is_default_ui
  type: BOOLEAN
  mode: NULLABLE
  description: Whether newtab opened with default UI configuration
- name: is_newtab_opened
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user opened a newtab during this visit
- name: is_search_issued
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user performed a search from newtab in default UI
- name: is_search_ad_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked a search ad in default UI
- name: is_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any Pocket content in default UI
- name: is_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked any Pocket content in default UI
- name: is_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any Pocket content was viewed in default UI
- name: is_sponsored_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored Pocket content in default 
    UI
- name: is_sponsored_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked sponsored Pocket content in default UI
- name: is_sponsored_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content was viewed in default UI
- name: any_content_click_count
  type: INTEGER
  description: Total clicks on Pocket content in default UI
- name: any_content_impression_count
  type: INTEGER
  description: Total Pocket content impressions in default UI
- name: organic_content_click_count
  type: INTEGER
  description: Clicks on organic Pocket content in default UI
- name: organic_content_impression_count
  type: INTEGER
  description: Organic Pocket content impressions in default UI
- name: sponsored_content_click_count
  type: INTEGER
  description: Clicks on sponsored Pocket content in default UI
- name: sponsored_content_impression_count
  type: INTEGER
  description: Sponsored Pocket content impressions in default UI
- name: is_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any topsite tile in default UI
- name: is_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked any topsite tile in default UI
- name: is_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any topsite tile was viewed in default UI
- name: is_sponsored_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored topsite in default UI
- name: is_sponsored_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked sponsored topsite in default UI
- name: is_sponsored_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsite was viewed in default UI
- name: any_topsite_click_count
  type: INTEGER
  description: Total clicks on topsite tiles in default UI
- name: any_topsite_impression_count
  type: INTEGER
  description: Total topsite tile impressions in default UI
- name: organic_topsite_click_count
  type: INTEGER
  description: Clicks on organic topsite tiles in default UI
- name: organic_topsite_impression_count
  type: INTEGER
  description: Organic topsite tile impressions in default UI
- name: sponsored_topsite_click_count
  type: INTEGER
  description: Clicks on sponsored topsite tiles in default UI
- name: sponsored_topsite_impression_count
  type: INTEGER
  description: Sponsored topsite tile impressions in default UI
- name: is_widget_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any widget in default UI
- name: is_wallpaper_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper features in default UI
- name: is_other_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper, topics, or sections in 
    default UI

  # Phase 4 Fields
- name: sample_id
  type: INTEGER
  description: A number, 0-99, that samples by client_id and allows filtering 
    data for analysis. It is a pipeline-generated artifact that should match 
    between pings.
- name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: geo_subdivision
  type: STRING
  description: State, province, or county subdivision within the country
- name: is_section
  type: BOOLEAN
  description: Whether visit had a Pocket section impression in default UI
- name: experiments
  type: RECORD
  mode: REPEATED
  description: Active experiments and branches associated with this visit
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier or slug name
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Assigned experiment branch name
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Experiment type classification
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique enrollment instance identifier
      description: Additional experiment metadata fields
    description: Experiment enrollment details and metadata
- name: newtab_weather_enabled
  type: BOOLEAN
  description: Whether weather widget is enabled on newtab
- name: default_search_engine
  type: STRING
  description: Default search engine ID for normal browsing
- name: default_private_search_engine
  type: STRING
  description: Default search engine ID for private browsing
- name: topsite_rows
  type: INTEGER
  description: Number of topsite tile rows configured to display
- name: topsite_sponsored_tiles_configured
  type: INTEGER
  description: Number of sponsored topsite tiles configured
- name: newtab_blocked_sponsors
  type: STRING
  mode: REPEATED
  description: Advertiser names dismissed by user
- name: organic_content_dismissal_count
  type: INTEGER
  description: Number of organic Pocket content dismissals
- name: sponsored_content_dismissal_count
  type: INTEGER
  description: Number of sponsored Pocket content dismissals
- name: organic_topsite_dismissal_count
  type: INTEGER
  description: Number of organic topsite dismissals
- name: sponsored_topsite_dismissal_count
  type: INTEGER
  description: Number of sponsored topsite dismissals
- name: any_interaction_count
  type: INTEGER
  description: Total user interactions across all newtab features
- name: search_interaction_count
  type: INTEGER
  description: Total search-related interactions
- name: nonsearch_interaction_count
  type: INTEGER
  description: Total non-search interactions
- name: any_content_interaction_count
  type: INTEGER
  description: Total Pocket content interactions
- name: organic_content_interaction_count
  type: INTEGER
  description: Organic Pocket content interactions
- name: sponsored_content_interaction_count
  type: INTEGER
  description: Sponsored Pocket content interactions
- name: any_topsite_interaction_count
  type: INTEGER
  description: Total topsite tile interactions
- name: organic_topsite_interaction_count
  type: INTEGER
  description: Organic topsite tile interactions
- name: sponsored_topsite_interaction_count
  type: INTEGER
  description: Sponsored topsite tile interactions
- name: content_thumbs_up_count
  type: INTEGER
  description: Positive feedback on Pocket content
- name: content_thumbs_down_count
  type: INTEGER
  description: Negative feedback on Pocket content
- name: search_ad_click_count
  type: INTEGER
  description: Number of search ad clicks
- name: search_ad_impression_count
  type: INTEGER
  description: Number of search ad impressions
- name: widget_interaction_count
  type: INTEGER
  description: Total widget interactions (weather, lists, timer)
- name: widget_impression_count
  type: INTEGER
  description: Total widget impressions
- name: other_interaction_count
  type: INTEGER
  description: Interactions with wallpaper, topics, or sections
- name: other_impression_count
  type: INTEGER
  description: Impressions of sections and other misc features
- name: newtab_visit_duration
  type: INTEGER
  description: Visit duration in milliseconds from open to close
- name: newtab_window_inner_height
  type: INTEGER
  description: Browser window height in pixels at visit start
- name: newtab_window_inner_width
  type: INTEGER
  description: Browser window width in pixels at visit start
