fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: newtab_visit_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for each newtab visit session
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: country
  type: STRING
  mode: NULLABLE
  description: Name of the country in which the activity took place, as 
    determined by the IP geolocation.
- name: homepage_category
  type: STRING
  mode: NULLABLE
  description: User's configured homepage or new window appearance preference
- name: newtab_category
  type: STRING
  mode: NULLABLE
  description: User's configured newtab page appearance preference
- name: organic_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled organic Pocket stories in newtab
- name: sponsored_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled sponsored Pocket stories in newtab
- name: sponsored_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled sponsored topsites in newtab
- name: organic_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled organic topsites in newtab
- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled search functionality in newtab
- name: is_default_ui
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the newtab visit used default UI configuration
- name: is_newtab_opened
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a newtab page was opened during this visit
- name: is_search_issued
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user issued a search query in default UI newtab
- name: is_search_ad_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked a search ad in default UI newtab
- name: is_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with Pocket content in default UI newtab
- name: is_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on Pocket content in default UI newtab
- name: is_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether Pocket content was displayed in default UI newtab
- name: is_sponsored_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored Pocket content in default 
    UI
- name: is_sponsored_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked sponsored Pocket content in default UI
- name: is_sponsored_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content was displayed in default UI
- name: any_content_click_count
  type: INTEGER
  description: Total clicks on any Pocket content in default UI newtab
- name: any_content_impression_count
  type: INTEGER
  description: Total impressions of any Pocket content in default UI newtab
- name: organic_content_click_count
  type: INTEGER
  description: Total clicks on organic Pocket content in default UI newtab
- name: organic_content_impression_count
  type: INTEGER
  description: Total impressions of organic Pocket content in default UI newtab
- name: sponsored_content_click_count
  type: INTEGER
  description: Total clicks on sponsored Pocket content in default UI newtab
- name: sponsored_content_impression_count
  type: INTEGER
  description: Total impressions of sponsored Pocket content in default UI 
    newtab
- name: is_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any topsite tile in default UI
- name: is_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked a topsite tile in default UI newtab
- name: is_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether topsite tiles were displayed in default UI newtab
- name: is_sponsored_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with a sponsored topsite in default UI
- name: is_sponsored_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked a sponsored topsite in default UI
- name: is_sponsored_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsites were displayed in default UI
- name: any_topsite_click_count
  type: INTEGER
  description: Total clicks on any topsite tiles in default UI newtab
- name: any_topsite_impression_count
  type: INTEGER
  description: Total impressions of topsite tiles in default UI newtab
- name: organic_topsite_click_count
  type: INTEGER
  description: Total clicks on organic topsite tiles in default UI newtab
- name: organic_topsite_impression_count
  type: INTEGER
  description: Total impressions of organic topsite tiles in default UI newtab
- name: sponsored_topsite_click_count
  type: INTEGER
  description: Total clicks on sponsored topsite tiles in default UI newtab
- name: sponsored_topsite_impression_count
  type: INTEGER
  description: Total impressions of sponsored topsite tiles in default UI newtab
- name: is_widget_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with widgets (weather, lists, timer) in 
    default UI
- name: is_wallpaper_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper features in default UI
- name: is_other_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper, topic selection, or 
    sections in default UI

  # Phase 4 Fields
- name: sample_id
  type: INTEGER
  description: A number, 0-99, that samples by client_id and allows filtering 
    data for analysis. It is a pipeline-generated artifact that should match 
    between pings.
- name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: geo_subdivision
  type: STRING
  description: First major country subdivision like state, province, or county
- name: is_section
  type: BOOLEAN
  description: Whether the visit had Pocket content impression belonging to a 
    section
- name: experiments
  type: RECORD
  mode: REPEATED
  description: Array of active experiments associated with this newtab visit
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier or slug name
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Experiment branch name assigned to the user
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Type or category of the experiment
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique identifier for user's enrollment in the experiment
      description: Additional experiment metadata including type and enrollment 
        ID
    description: Experiment assignment details including branch and enrollment
- name: newtab_weather_enabled
  type: BOOLEAN
  description: Whether the weather widget is enabled on newtab
- name: default_search_engine
  type: STRING
  description: Engine ID of the user's default search engine
- name: default_private_search_engine
  type: STRING
  description: Engine ID of the default search engine for private browsing
- name: topsite_rows
  type: INTEGER
  description: Number of topsite tile rows configured to display on newtab
- name: topsite_sponsored_tiles_configured
  type: INTEGER
  description: Number of sponsored topsite tiles configured to display
- name: newtab_blocked_sponsors
  type: STRING
  mode: REPEATED
  description: List of advertiser names dismissed or blocked by the user
- name: organic_content_dismissal_count
  type: INTEGER
  description: Total dismissals of organic Pocket content in default UI
- name: sponsored_content_dismissal_count
  type: INTEGER
  description: Total dismissals of sponsored Pocket content in default UI
- name: organic_topsite_dismissal_count
  type: INTEGER
  description: Total dismissals of organic topsite tiles in default UI
- name: sponsored_topsite_dismissal_count
  type: INTEGER
  description: Total dismissals of sponsored topsite tiles in default UI
- name: any_interaction_count
  type: INTEGER
  description: Total count of all user interactions in default UI newtab
- name: search_interaction_count
  type: INTEGER
  description: Total count of search-related interactions in default UI
- name: nonsearch_interaction_count
  type: INTEGER
  description: Total count of non-search interactions in default UI
- name: any_content_interaction_count
  type: INTEGER
  description: Total interactions with any Pocket content in default UI
- name: organic_content_interaction_count
  type: INTEGER
  description: Total interactions with organic Pocket content in default UI
- name: sponsored_content_interaction_count
  type: INTEGER
  description: Total interactions with sponsored Pocket content in default UI
- name: any_topsite_interaction_count
  type: INTEGER
  description: Total interactions with any topsite tiles in default UI
- name: organic_topsite_interaction_count
  type: INTEGER
  description: Total interactions with organic topsite tiles in default UI
- name: sponsored_topsite_interaction_count
  type: INTEGER
  description: Total interactions with sponsored topsite tiles in default UI
- name: content_thumbs_up_count
  type: INTEGER
  description: Total thumbs up votes on Pocket content in default UI
- name: content_thumbs_down_count
  type: INTEGER
  description: Total thumbs down votes on Pocket content in default UI
- name: search_ad_click_count
  type: INTEGER
  description: Total clicks on search advertisements in default UI newtab
- name: search_ad_impression_count
  type: INTEGER
  description: Total impressions of search advertisements in default UI newtab
- name: widget_interaction_count
  type: INTEGER
  description: Total interactions with widgets (weather, lists, timer) in 
    default UI
- name: widget_impression_count
  type: INTEGER
  description: Total impressions of widgets in default UI newtab
- name: other_interaction_count
  type: INTEGER
  description: Total miscellaneous interactions (wallpaper, topics, sections) in
    default UI
- name: other_impression_count
  type: INTEGER
  description: Total miscellaneous impressions in default UI newtab
- name: newtab_visit_duration
  type: INTEGER
  description: Duration of newtab visit in milliseconds (from open to close 
    event)
- name: newtab_window_inner_height
  type: INTEGER
  description: Browser window inner height in pixels during newtab open
- name: newtab_window_inner_width
  type: INTEGER
  description: Browser window inner width in pixels during newtab open
