fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date when the telemetry data was submitted

- name: client_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for the Firefox client

- name: newtab_visit_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for a specific new tab visit session

- name: app_version
  type: INT64
  mode: NULLABLE
  description: Major version number of the Firefox application

- name: os
  type: STRING
  mode: NULLABLE
  description: Normalized operating system name

- name: channel
  type: STRING
  mode: NULLABLE
  description: Firefox release channel (release, beta, nightly, etc.)

- name: locale
  type: STRING
  mode: NULLABLE
  description: User's locale setting

- name: country
  type: STRING
  mode: NULLABLE
  description: Normalized country code based on user's location

- name: homepage_category
  type: STRING
  mode: NULLABLE
  description: Category configuration for the homepage

- name: newtab_category
  type: STRING
  mode: NULLABLE
  description: Category configuration for the new tab page

- name: organic_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether organic Pocket content is enabled

- name: sponsored_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content is enabled

- name: sponsored_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsites are enabled

- name: organic_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether organic topsites are enabled

- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether search functionality is enabled on the new tab page

- name: is_default_ui
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the visit was opened in the default UI configuration

- name: is_newtab_opened
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a new tab was opened during this visit

- name: is_search_issued
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a search was issued from the new tab page (default UI only)

- name: is_search_ad_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a search ad was clicked during this visit (default UI only)

- name: is_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with Pocket content (click, dismiss, or thumbs) (default UI only)

- name: is_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on Pocket content (default UI only)

- name: is_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether Pocket content impressions occurred (default UI only)

- name: is_sponsored_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored Pocket content (default UI only)

- name: is_sponsored_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on sponsored Pocket content (default UI only)

- name: is_sponsored_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content impressions occurred (default UI only)

- name: any_content_click_count
  type: INT64
  mode: NULLABLE
  description: Total count of clicks on any Pocket content (default UI only)

- name: any_content_impression_count
  type: INT64
  mode: NULLABLE
  description: Total count of impressions for any Pocket content (default UI only)

- name: organic_content_click_count
  type: INT64
  mode: NULLABLE
  description: Count of clicks on organic (non-sponsored) Pocket content (default UI only)

- name: organic_content_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of impressions for organic Pocket content (default UI only)

- name: sponsored_content_click_count
  type: INT64
  mode: NULLABLE
  description: Count of clicks on sponsored Pocket content (default UI only)

- name: sponsored_content_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of impressions for sponsored Pocket content (default UI only)

- name: is_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with topsites (click or dismiss) (default UI only)

- name: is_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on a topsite (default UI only)

- name: is_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether topsite impressions occurred (default UI only)

- name: is_sponsored_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored topsites (default UI only)

- name: is_sponsored_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on a sponsored topsite (default UI only)

- name: is_sponsored_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsite impressions occurred (default UI only)

- name: any_topsite_click_count
  type: INT64
  mode: NULLABLE
  description: Total count of clicks on any topsite (default UI only)

- name: any_topsite_impression_count
  type: INT64
  mode: NULLABLE
  description: Total count of impressions for any topsite (default UI only)

- name: organic_topsite_click_count
  type: INT64
  mode: NULLABLE
  description: Count of clicks on organic topsites (default UI only)

- name: organic_topsite_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of impressions for organic topsites (default UI only)

- name: sponsored_topsite_click_count
  type: INT64
  mode: NULLABLE
  description: Count of clicks on sponsored topsites (default UI only)

- name: sponsored_topsite_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of impressions for sponsored topsites (default UI only)

- name: is_widget_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with widgets (weather, lists, timer) (default UI only)

- name: is_wallpaper_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper features (default UI only)

- name: is_other_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user had other interactions (wallpaper, topic selection, sections, inline selection) (default UI only)

- name: sample_id
  type: INT64
  mode: NULLABLE
  description: Sample identifier for the client

- name: profile_group_id
  type: STRING
  mode: NULLABLE
  description: Legacy telemetry profile group identifier

- name: geo_subdivision
  type: STRING
  mode: NULLABLE
  description: Geographic subdivision (e.g., state or province)

- name: is_section
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the visit includes section impressions with section position data (default UI only)

- name: experiments
  type: RECORD
  mode: REPEATED
  description: Active experiments during this visit
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier
  - name: value
    type: STRING
    mode: NULLABLE
    description: Experiment branch or value

- name: newtab_weather_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether weather widget is enabled on the new tab page

- name: default_search_engine
  type: STRING
  mode: NULLABLE
  description: Default search engine identifier

- name: default_private_search_engine
  type: STRING
  mode: NULLABLE
  description: Default search engine for private browsing

- name: topsite_rows
  type: INT64
  mode: NULLABLE
  description: Number of topsite rows configured

- name: topsite_sponsored_tiles_configured
  type: INT64
  mode: NULLABLE
  description: Number of sponsored topsite tiles configured

- name: newtab_blocked_sponsors
  type: STRING
  mode: REPEATED
  description: List of blocked sponsor identifiers

- name: organic_content_dismissal_count
  type: INT64
  mode: NULLABLE
  description: Count of organic Pocket content dismissals (default UI only)

- name: sponsored_content_dismissal_count
  type: INT64
  mode: NULLABLE
  description: Count of sponsored Pocket content dismissals (default UI only)

- name: organic_topsite_dismissal_count
  type: INT64
  mode: NULLABLE
  description: Count of organic topsite dismissals (default UI only)

- name: sponsored_topsite_dismissal_count
  type: INT64
  mode: NULLABLE
  description: Count of sponsored topsite dismissals (default UI only)

- name: any_interaction_count
  type: INT64
  mode: NULLABLE
  description: Total count of all interactions including search and non-search (default UI only)

- name: search_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of search-related interactions (default UI only)

- name: nonsearch_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of non-search interactions (default UI only)

- name: any_content_interaction_count
  type: INT64
  mode: NULLABLE
  description: Total count of Pocket content interactions (default UI only)

- name: organic_content_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of organic Pocket content interactions (default UI only)

- name: sponsored_content_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of sponsored Pocket content interactions (default UI only)

- name: any_topsite_interaction_count
  type: INT64
  mode: NULLABLE
  description: Total count of topsite interactions (default UI only)

- name: organic_topsite_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of organic topsite interactions (default UI only)

- name: sponsored_topsite_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of sponsored topsite interactions (default UI only)

- name: content_thumbs_up_count
  type: INT64
  mode: NULLABLE
  description: Count of thumbs up votes on Pocket content (default UI only)

- name: content_thumbs_down_count
  type: INT64
  mode: NULLABLE
  description: Count of thumbs down votes on Pocket content (default UI only)

- name: search_ad_click_count
  type: INT64
  mode: NULLABLE
  description: Count of search ad clicks (default UI only)

- name: search_ad_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of search ad impressions (default UI only)

- name: widget_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of widget interactions (weather, lists, timer) (default UI only)

- name: widget_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of widget impressions (default UI only)

- name: other_interaction_count
  type: INT64
  mode: NULLABLE
  description: Count of other interactions (wallpaper, topic selection, sections) (default UI only)

- name: other_impression_count
  type: INT64
  mode: NULLABLE
  description: Count of other impressions (sections) (default UI only)

- name: newtab_visit_duration
  type: INT64
  mode: NULLABLE
  description: Duration of the new tab visit in milliseconds (time between opened and closed events)

- name: newtab_window_inner_height
  type: INT64
  mode: NULLABLE
  description: Inner height of the new tab window in pixels

- name: newtab_window_inner_width
  type: INT64
  mode: NULLABLE
  description: Inner width of the new tab window in pixels

- name: topsite_tile_components
  type: RECORD
  mode: REPEATED
  description: Detailed metrics for individual topsite tiles during this visit
  fields:
  - name: tile_id
    type: STRING
    mode: NULLABLE
    description: Unique identifier for the topsite tile
  - name: position
    type: INT64
    mode: NULLABLE
    description: Position of the tile on the new tab page
  - name: is_sponsored
    type: BOOLEAN
    mode: NULLABLE
    description: Whether the tile is a sponsored topsite
  - name: impression_count
    type: INT64
    mode: NULLABLE
    description: Number of impressions for this tile
  - name: click_count
    type: INT64
    mode: NULLABLE
    description: Number of clicks on this tile
  - name: dismissal_count
    type: INT64
    mode: NULLABLE
    description: Number of dismissals for this tile
  - name: pin_count
    type: INT64
    mode: NULLABLE
    description: Number of times this tile was pinned
  - name: unpin_count
    type: INT64
    mode: NULLABLE
    description: Number of times this tile was unpinned

- name: content_position_components
  type: RECORD
  mode: REPEATED
  description: Detailed metrics for Pocket content at specific positions during this visit
  fields:
  - name: position
    type: INT64
    mode: NULLABLE
    description: Position of the content item on the new tab page
  - name: is_sponsored
    type: BOOLEAN
    mode: NULLABLE
    description: Whether the content is sponsored
  - name: section_position
    type: INT64
    mode: NULLABLE
    description: Position of the section containing this content
  - name: format
    type: STRING
    mode: NULLABLE
    description: Format of the content item
  - name: is_section_followed
    type: BOOLEAN
    mode: NULLABLE
    description: Whether the section is followed by the user
  - name: impression_count
    type: INT64
    mode: NULLABLE
    description: Number of impressions for this content item
  - name: click_count
    type: INT64
    mode: NULLABLE
    description: Number of clicks on this content item
  - name: dismissal_count
    type: INT64
    mode: NULLABLE
    description: Number of dismissals for this content item
  - name: thumbs_up_count
    type: INT64
    mode: NULLABLE
    description: Number of thumbs up votes for this content
  - name: thumbs_down_count
    type: INT64
    mode: NULLABLE
    description: Number of thumbs down votes for this content
