fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: newtab_visit_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for each newtab visit session
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: country
  type: STRING
  mode: NULLABLE
  description: Name of the country in which the activity took place, as 
    determined by the IP geolocation.
- name: homepage_category
  type: STRING
  mode: NULLABLE
  description: User's configured homepage appearance setting
- name: newtab_category
  type: STRING
  mode: NULLABLE
  description: User's configured new tab page appearance setting
- name: organic_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled Pocket organic stories
- name: sponsored_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled Pocket sponsored stories
- name: sponsored_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled sponsored topsites
- name: organic_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled organic topsites
- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled search functionality on newtab
- name: is_default_ui
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the newtab was opened in default UI configuration
- name: is_newtab_opened
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a newtab was opened during this visit
- name: is_search_issued
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user issued a search from newtab in default UI
- name: is_search_ad_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on a search ad in default UI
- name: is_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any Pocket content in default UI
- name: is_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on any Pocket content in default UI
- name: is_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any Pocket content was impressed in default UI
- name: is_sponsored_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored Pocket content in default 
    UI
- name: is_sponsored_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on sponsored Pocket content in default UI
- name: is_sponsored_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content was impressed in default UI
- name: any_content_click_count
  type: INTEGER
  description: Total count of clicks on Pocket content in default UI
- name: any_content_impression_count
  type: INTEGER
  description: Total count of Pocket content impressions in default UI
- name: organic_content_click_count
  type: INTEGER
  description: Count of clicks on organic Pocket content in default UI
- name: organic_content_impression_count
  type: INTEGER
  description: Count of organic Pocket content impressions in default UI
- name: sponsored_content_click_count
  type: INTEGER
  description: Count of clicks on sponsored Pocket content in default UI
- name: sponsored_content_impression_count
  type: INTEGER
  description: Count of sponsored Pocket content impressions in default UI
- name: is_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any topsite in default UI
- name: is_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on any topsite in default UI
- name: is_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any topsite was impressed in default UI
- name: is_sponsored_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored topsite in default UI
- name: is_sponsored_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on sponsored topsite in default UI
- name: is_sponsored_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsite was impressed in default UI
- name: any_topsite_click_count
  type: INTEGER
  description: Total count of clicks on topsites in default UI
- name: any_topsite_impression_count
  type: INTEGER
  description: Total count of topsite impressions in default UI
- name: organic_topsite_click_count
  type: INTEGER
  description: Count of clicks on organic topsites in default UI
- name: organic_topsite_impression_count
  type: INTEGER
  description: Count of organic topsite impressions in default UI
- name: sponsored_topsite_click_count
  type: INTEGER
  description: Count of clicks on sponsored topsites in default UI
- name: sponsored_topsite_impression_count
  type: INTEGER
  description: Count of sponsored topsite impressions in default UI
- name: is_widget_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any widget (weather, lists, timer) 
    in default UI
- name: is_wallpaper_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper features in default UI
- name: is_other_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with wallpaper, topic selection, or 
    sections in default UI

  # Phase 4 Fields
- name: sample_id
  type: INTEGER
  description: A number, 0-99, that samples by client_id and allows filtering 
    data for analysis. It is a pipeline-generated artifact that should match 
    between pings.
- name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: geo_subdivision
  type: STRING
  description: First major country subdivision such as state, province, or 
    county
- name: is_section
  type: BOOLEAN
  description: Whether visit included Pocket content impression within a section
    in default UI
- name: experiments
  type: RECORD
  mode: REPEATED
  description: Array of active experiments associated with the visit
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier key
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Experiment branch assignment for the user
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Type classification of the experiment
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique identifier for the experiment enrollment instance
      description: Additional experiment metadata
    description: Experiment configuration details
- name: newtab_weather_enabled
  type: BOOLEAN
  description: Whether weather widget is enabled on newtab
- name: default_search_engine
  type: STRING
  description: Engine ID of the default search engine configured
- name: default_private_search_engine
  type: STRING
  description: Engine ID of the default private browsing search engine
- name: topsite_rows
  type: INTEGER
  description: Number of topsite rows configured to display on newtab
- name: topsite_sponsored_tiles_configured
  type: INTEGER
  description: Number of sponsored topsite tiles configured for display
- name: newtab_blocked_sponsors
  type: STRING
  mode: REPEATED
  description: List of advertiser names dismissed by user
- name: organic_content_dismissal_count
  type: INTEGER
  description: Count of organic Pocket content dismissals in default UI
- name: sponsored_content_dismissal_count
  type: INTEGER
  description: Count of sponsored Pocket content dismissals in default UI
- name: organic_topsite_dismissal_count
  type: INTEGER
  description: Count of organic topsite dismissals in default UI
- name: sponsored_topsite_dismissal_count
  type: INTEGER
  description: Count of sponsored topsite dismissals in default UI
- name: any_interaction_count
  type: INTEGER
  description: Total count of all user interactions in default UI
- name: search_interaction_count
  type: INTEGER
  description: Count of search-related interactions in default UI
- name: nonsearch_interaction_count
  type: INTEGER
  description: Count of non-search interactions in default UI
- name: any_content_interaction_count
  type: INTEGER
  description: Total count of Pocket content interactions in default UI
- name: organic_content_interaction_count
  type: INTEGER
  description: Count of organic Pocket content interactions in default UI
- name: sponsored_content_interaction_count
  type: INTEGER
  description: Count of sponsored Pocket content interactions in default UI
- name: any_topsite_interaction_count
  type: INTEGER
  description: Total count of topsite interactions in default UI
- name: organic_topsite_interaction_count
  type: INTEGER
  description: Count of organic topsite interactions in default UI
- name: sponsored_topsite_interaction_count
  type: INTEGER
  description: Count of sponsored topsite interactions in default UI
- name: content_thumbs_up_count
  type: INTEGER
  description: Count of thumbs up votes on Pocket content in default UI
- name: content_thumbs_down_count
  type: INTEGER
  description: Count of thumbs down votes on Pocket content in default UI
- name: search_ad_click_count
  type: INTEGER
  description: Count of search ad clicks in default UI
- name: search_ad_impression_count
  type: INTEGER
  description: Count of search ad impressions in default UI
- name: widget_interaction_count
  type: INTEGER
  description: Count of widget interactions (weather, lists, timer) in default 
    UI
- name: widget_impression_count
  type: INTEGER
  description: Count of widget impressions in default UI
- name: other_interaction_count
  type: INTEGER
  description: Count of miscellaneous interactions (wallpaper, topics, sections)
    in default UI
- name: other_impression_count
  type: INTEGER
  description: Count of miscellaneous impressions in default UI
- name: newtab_visit_duration
  type: INTEGER
  description: Duration of newtab visit in milliseconds from open to close event
- name: newtab_window_inner_height
  type: INTEGER
  description: Browser window height in pixels at newtab open
- name: newtab_window_inner_width
  type: INTEGER
  description: Browser window width in pixels at newtab open
