fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: newtab_visit_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier for each newtab visit session, used to group 
    events within a single visit
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the 
    client.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Set of language- and/or country-based preferences for a user 
    interface.
- name: country
  type: STRING
  mode: NULLABLE
  description: Name of the country in which the activity took place, as 
    determined by the IP geolocation.
- name: homepage_category
  type: STRING
  mode: NULLABLE
  description: User-configured homepage appearance setting (e.g., enabled, 
    disabled, custom)
- name: newtab_category
  type: STRING
  mode: NULLABLE
  description: User-configured new tab appearance setting (e.g., enabled, 
    disabled, custom)
- name: organic_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled Pocket organic stories in Firefox newtab
- name: sponsored_content_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled Pocket sponsored stories in Firefox 
    newtab
- name: sponsored_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled sponsored topsite tiles in Firefox 
    newtab
- name: organic_topsites_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled organic topsite tiles in Firefox newtab
- name: newtab_search_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user has enabled the search bar on Firefox newtab page
- name: is_default_ui
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the newtab visit displayed the default Firefox UI 
    configuration
- name: is_newtab_opened
  type: BOOLEAN
  mode: NULLABLE
  description: Whether a newtab page was opened during this visit session
- name: is_search_issued
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user performed a search query on newtab with default UI
- name: is_search_ad_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked a search advertisement on newtab with 
    default UI
- name: is_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any Pocket content (click, dismiss, 
    or vote) with default UI
- name: is_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on any Pocket content story with default UI
- name: is_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any Pocket content was displayed to the user with default
    UI
- name: is_sponsored_content_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored Pocket content with 
    default UI
- name: is_sponsored_content_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on sponsored Pocket content with default UI
- name: is_sponsored_content_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored Pocket content was displayed with default UI
- name: any_content_click_count
  type: INTEGER
  description: Total number of clicks on any Pocket content during the visit 
    with default UI
- name: any_content_impression_count
  type: INTEGER
  description: Total number of Pocket content impressions displayed during the 
    visit with default UI
- name: organic_content_click_count
  type: INTEGER
  description: Total number of clicks on organic Pocket content during the visit
    with default UI
- name: organic_content_impression_count
  type: INTEGER
  description: Total number of organic Pocket content impressions during the 
    visit with default UI
- name: sponsored_content_click_count
  type: INTEGER
  description: Total number of clicks on sponsored Pocket content during the 
    visit with default UI
- name: sponsored_content_impression_count
  type: INTEGER
  description: Total number of sponsored Pocket content impressions during the 
    visit with default UI
- name: is_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with any topsite tile (click or dismiss) 
    with default UI
- name: is_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on any topsite tile with default UI
- name: is_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether any topsite tiles were displayed to the user with default
    UI
- name: is_sponsored_topsite_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with sponsored topsite tiles with default
    UI
- name: is_sponsored_topsite_click
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user clicked on a sponsored topsite tile with default UI
- name: is_sponsored_topsite_impression
  type: BOOLEAN
  mode: NULLABLE
  description: Whether sponsored topsite tiles were displayed with default UI
- name: any_topsite_click_count
  type: INTEGER
  description: Total number of clicks on any topsite tiles during the visit with
    default UI
- name: any_topsite_impression_count
  type: INTEGER
  description: Total number of topsite tile impressions during the visit with 
    default UI
- name: organic_topsite_click_count
  type: INTEGER
  description: Total number of clicks on organic topsite tiles during the visit 
    with default UI
- name: organic_topsite_impression_count
  type: INTEGER
  description: Total number of organic topsite tile impressions during the visit
    with default UI
- name: sponsored_topsite_click_count
  type: INTEGER
  description: Total number of clicks on sponsored topsite tiles during the 
    visit with default UI
- name: sponsored_topsite_impression_count
  type: INTEGER
  description: Total number of sponsored topsite tile impressions during the 
    visit with default UI
- name: is_widget_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with newtab widgets (weather, lists, 
    timer) with default UI
- name: is_wallpaper_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with newtab wallpaper features with 
    default UI
- name: is_other_interaction
  type: BOOLEAN
  mode: NULLABLE
  description: Whether user interacted with other newtab features (wallpaper, 
    topics, sections) with default UI

  # Phase 4 Fields
- name: sample_id
  type: INTEGER
  description: A number, 0-99, that samples by client_id and allows filtering 
    data for analysis. It is a pipeline-generated artifact that should match 
    between pings.
- name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with 
    other telemetry data.
- name: geo_subdivision
  type: STRING
  description: First-level administrative subdivision of the country (state, 
    province, or county)
- name: is_section
  type: BOOLEAN
  description: Whether the visit included an impression of content within a 
    defined newtab section with default UI
- name: experiments
  type: RECORD
  mode: REPEATED
  description: Nested array of active experiments associated with this newtab 
    visit, including branch and enrollment metadata
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Experiment identifier or slug name for the active experiment
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
      description: Experiment branch or variant assigned to the user (e.g., 
        control, treatment)
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
        description: Classification of the experiment type (e.g., 
          nimbus-experiment, normandy-experiment)
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
        description: Unique identifier for the user's enrollment in this 
          specific experiment
      description: Additional experiment metadata including type and enrollment 
        tracking information
    description: Nested record containing experiment assignment details 
      including branch and metadata
- name: newtab_weather_enabled
  type: BOOLEAN
  description: Whether the weather widget is enabled on the newtab page
- name: default_search_engine
  type: STRING
  description: Identifier of the default search engine configured in Firefox
- name: default_private_search_engine
  type: STRING
  description: Identifier of the default search engine for private browsing mode
- name: topsite_rows
  type: INTEGER
  description: Number of topsite tile rows configured to display on the newtab 
    page
- name: topsite_sponsored_tiles_configured
  type: INTEGER
  description: Number of sponsored topsite tiles configured to display on newtab
    page
- name: newtab_blocked_sponsors
  type: STRING
  mode: REPEATED
  description: Array of advertiser names that have been dismissed or blocked by 
    the user
- name: organic_content_dismissal_count
  type: INTEGER
  description: Total number of organic Pocket content items dismissed during the
    visit with default UI
- name: sponsored_content_dismissal_count
  type: INTEGER
  description: Total number of sponsored Pocket content items dismissed during 
    the visit with default UI
- name: organic_topsite_dismissal_count
  type: INTEGER
  description: Total number of organic topsite tiles dismissed during the visit 
    with default UI
- name: sponsored_topsite_dismissal_count
  type: INTEGER
  description: Total number of sponsored topsite tiles dismissed during the 
    visit with default UI
- name: any_interaction_count
  type: INTEGER
  description: Total count of all user interactions on newtab during the visit 
    with default UI
- name: search_interaction_count
  type: INTEGER
  description: Total count of search-related interactions during the visit with 
    default UI
- name: nonsearch_interaction_count
  type: INTEGER
  description: Total count of non-search interactions (content, topsites, 
    widgets) with default UI
- name: any_content_interaction_count
  type: INTEGER
  description: Total count of all Pocket content interactions (clicks, 
    dismissals, votes) with default UI
- name: organic_content_interaction_count
  type: INTEGER
  description: Total count of organic Pocket content interactions during the 
    visit with default UI
- name: sponsored_content_interaction_count
  type: INTEGER
  description: Total count of sponsored Pocket content interactions during the 
    visit with default UI
- name: any_topsite_interaction_count
  type: INTEGER
  description: Total count of all topsite interactions (clicks, dismissals) with
    default UI
- name: organic_topsite_interaction_count
  type: INTEGER
  description: Total count of organic topsite interactions during the visit with
    default UI
- name: sponsored_topsite_interaction_count
  type: INTEGER
  description: Total count of sponsored topsite interactions during the visit 
    with default UI
- name: content_thumbs_up_count
  type: INTEGER
  description: Total count of positive votes (thumbs up) on Pocket content with 
    default UI
- name: content_thumbs_down_count
  type: INTEGER
  description: Total count of negative votes (thumbs down) on Pocket content 
    with default UI
- name: search_ad_click_count
  type: INTEGER
  description: Total count of search advertisement clicks during the visit with 
    default UI
- name: search_ad_impression_count
  type: INTEGER
  description: Total count of search advertisements displayed during the visit 
    with default UI
- name: widget_interaction_count
  type: INTEGER
  description: Total count of widget interactions (weather, lists, timer) during
    the visit with default UI
- name: widget_impression_count
  type: INTEGER
  description: Total count of widget impressions displayed during the visit with
    default UI
- name: other_interaction_count
  type: INTEGER
  description: Total count of miscellaneous interactions (wallpaper, topics, 
    sections) with default UI
- name: other_impression_count
  type: INTEGER
  description: Total count of miscellaneous impressions (sections) displayed 
    with default UI
- name: newtab_visit_duration
  type: INTEGER
  description: Duration of the newtab visit in milliseconds, calculated from 
    open to close event
- name: newtab_window_inner_height
  type: INTEGER
  description: Height of the browser window in pixels at newtab open
- name: newtab_window_inner_width
  type: INTEGER
  description: Width of the browser window in pixels at newtab open
