fields:
- name: ga_client_id
  mode: NULLABLE
  type: STRING
  description: Unique identifier for Google Analytics client using cookie-based 
    tracking on mozilla.org
- name: ga_session_id
  mode: NULLABLE
  type: STRING
  description: Unique session identifier assigned by Google Analytics for 
    tracking user sessions
- name: session_date
  mode: NULLABLE
  type: DATE
  description: Date when the session started, used for time-based analysis and 
    partitioning
- name: session_start_timestamp
  mode: NULLABLE
  type: DATETIME
  description: |-
    Timestamp of session_start event or minimum event timestamp if no session_start exists
- name: is_first_session
  mode: NULLABLE
  type: BOOLEAN
  description: Boolean flag indicating if this is the user's first session on 
    mozilla.org
- name: session_number
  mode: NULLABLE
  type: INTEGER
  description: Sequential session counter for each client starting at 1
- name: time_on_site
  mode: NULLABLE
  type: INTEGER
  description: Session duration in seconds between first and last event
- name: pageviews
  mode: NULLABLE
  type: INTEGER
  description: Count of page_view events during the session
- name: country
  type: STRING
  mode: NULLABLE
  description: |-
    Name of the country in which the activity took place, as determined by the IP geolocation.
- name: region
  type: STRING
  mode: NULLABLE
  description: Geographic region from session_start event for location-based 
    analysis
- name: city
  type: STRING
  mode: NULLABLE
  description: City location from session_start event for granular geographic 
    insights
- name: device_category
  type: STRING
  mode: NULLABLE
  description: Device type classification (Mobile, Tablet, Desktop) from 
    session_start event
- name: mobile_device_model
  type: STRING
  mode: NULLABLE
  description: Mobile device model name from session_start event for device 
    analysis
- name: mobile_device_string
  type: STRING
  mode: NULLABLE
  description: |-
    Mobile device branding and marketing name from session_start event
- name: os
  type: STRING
  mode: NULLABLE
  description: "Operating system name (e.g. Macintosh, Windows) from session_start
    event"
- name: os_version
  type: STRING
  mode: NULLABLE
  description: "Operating system version string from session_start event"
- name: language
  type: STRING
  mode: NULLABLE
  description: |-
    Device language setting as IETF language code from session_start event
- name: browser
  type: STRING
  mode: NULLABLE
  description: "Browser name (e.g. Chrome, Firefox) from session_start event"
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: "Browser version string from session_start event"
- name: first_campaign_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null campaign value extracted from event_params during the
    session"
- name: distinct_campaigns_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique campaigns captured in event_params throughout
    the session"
- name: first_source_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null traffic source extracted from event_params during the
    session"
- name: distinct_sources_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique traffic sources captured in event_params throughout
    the session"
- name: first_medium_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null medium value extracted from event_params during the
    session"
- name: distinct_mediums_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique mediums captured in event_params throughout the
    session"
- name: first_content_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null content value extracted from event_params during the
    session"
- name: distinct_contents_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique content values captured in event_params throughout
    the session"
- name: manual_campaign_id
  type: STRING
  mode: NULLABLE
  description: Campaign ID from collected_traffic_source at session_start for 
    manual tracking
- name: manual_campaign_name
  type: STRING
  mode: NULLABLE
  description: Campaign name from collected_traffic_source at session_start for 
    manual tracking
- name: manual_source
  type: STRING
  mode: NULLABLE
  description: |-
    Traffic source from collected_traffic_source at session_start for attribution
- name: manual_medium
  type: STRING
  mode: NULLABLE
  description: |-
    Traffic medium (organic, cpc, referral, utm_medium) from collected_traffic_source at session_start
- name: manual_term
  type: STRING
  mode: NULLABLE
  description: Search term from collected_traffic_source at session_start for 
    keyword analysis
- name: manual_content
  type: STRING
  mode: NULLABLE
  description: Ad content identifier from collected_traffic_source at 
    session_start
- name: gclid
  type: STRING
  mode: NULLABLE
  description: Last reported Google Click ID for tracking Google Ads clicks
- name: gclid_array
  type: STRING
  mode: REPEATED
  description: Array of all Google Click IDs reported during the session
- name: had_download_event
  type: BOOLEAN
  mode: NULLABLE
  description: "Boolean indicating if any Firefox download event occurred during the
    session"
- name: firefox_desktop_downloads
  type: INT64
  mode: NULLABLE
  description: "Count of Firefox desktop download events in the session"
- name: last_reported_install_target
  type: STRING
  mode: NULLABLE
  description: "Most recent install target (e.g. desktop_release, android_beta) from
    the session"
- name: all_reported_install_targets
  type: STRING
  mode: REPEATED
  description: "Array of all install targets reported during the session"
- name: last_reported_stub_session_id
  type: STRING
  mode: NULLABLE
  description: "Most recent Stub Session ID for joining with dl_ga_triplets to get
    dl_tokens"
- name: all_reported_stub_session_ids
  type: STRING
  mode: REPEATED
  description: "Array of all Stub Session IDs reported during the session for download
    tracking"
- name: landing_screen
  type: STRING
  mode: NULLABLE
  description: "First page location URL for the session, typically the entry point"
- name: first_term_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null search term extracted from event_params during the
    session"
- name: distinct_terms_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique search terms captured in event_params throughout
    the session"
- name: ad_google_campaign
  type: STRING
  mode: NULLABLE
  description: Google Ads campaign name from session_start for paid campaign 
    tracking
- name: ad_google_campaign_id
  type: STRING
  mode: NULLABLE
  description: Google Ads campaign ID from session_start for paid campaign 
    analysis
- name: ad_google_group
  type: STRING
  mode: NULLABLE
  description: Google Ads ad group name from session_start for campaign 
    structure analysis
- name: ad_google_group_id
  type: STRING
  mode: NULLABLE
  description: Google Ads ad group ID from session_start for detailed ad 
    performance
- name: ad_google_account
  type: STRING
  mode: NULLABLE
  description: Google Ads account name from session_start for account-level 
    analysis
- name: ad_crosschannel_source
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign source from Google Ads at session_start
- name: ad_crosschannel_medium
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign medium from Google Ads at session_start
- name: ad_crosschannel_campaign
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign name from Google Ads at session_start
- name: ad_crosschannel_campaign_id
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign ID from Google Ads at session_start
- name: ad_crosschannel_source_platform
  type: STRING
  mode: NULLABLE
  description: Platform identifier for cross-channel campaigns from Google Ads 
    at session_start
- name: ad_crosschannel_primary_channel_group
  type: STRING
  mode: NULLABLE
  description: Primary channel grouping for cross-channel campaigns from Google 
    Ads at session_start
- name: ad_crosschannel_default_channel_group
  type: STRING
  mode: NULLABLE
  description: Default channel grouping for cross-channel campaigns from Google 
    Ads at session_start
- name: first_experiment_id_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null experiment ID extracted from event_params for A/B 
    testing
- name: distinct_experiment_ids_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique experiment IDs captured in event_params for 
    experiment tracking
- name: first_experiment_branch_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null experiment branch extracted from event_params for 
    variant analysis
- name: distinct_experiment_branches_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique experiment branches captured in event_params 
    for test variants
- name: first_gad_campaignid_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null Google Ads campaign ID extracted from event_params
- name: distinct_gad_campaignid_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique Google Ads campaign IDs captured in 
    event_params
