fields:
- name: ga_client_id
  mode: NULLABLE
  type: STRING
  description: Unique identifier for a Google Analytics client, derived from a 
    cookie set on mozilla.org
- name: ga_session_id
  mode: NULLABLE
  type: STRING
  description: Unique identifier for a Google Analytics session, cast as string 
    from event parameters
- name: session_date
  mode: NULLABLE
  type: DATE
  description: Date when the session started, derived from session_start event 
    or first event timestamp
- name: session_start_timestamp
  mode: NULLABLE
  type: DATETIME
  description: |-
    Timestamp of the session_start event; defaults to minimum event timestamp if no session_start event exists
- name: is_first_session
  mode: NULLABLE
  type: BOOLEAN
  description: Indicates whether this is the first session for the client 
    (session_number = 1)
- name: session_number
  mode: NULLABLE
  type: INTEGER
  description: Sequential session count for this client, starting at 1 and 
    incrementing with each new session
- name: time_on_site
  mode: NULLABLE
  type: INTEGER
  description: Duration in seconds between the first and last event of the 
    session
- name: pageviews
  mode: NULLABLE
  type: INTEGER
  description: Total number of page_view events recorded during this session
- name: country
  type: STRING
  mode: NULLABLE
  description: |-
    Name of the country in which the activity took place, as determined by the IP geolocation.
- name: region
  type: STRING
  mode: NULLABLE
  description: Geographic region from session_start event geo data
- name: city
  type: STRING
  mode: NULLABLE
  description: City location from session_start event geo data
- name: device_category
  type: STRING
  mode: NULLABLE
  description: Type of device used (Mobile, Tablet, or Desktop) from 
    session_start event
- name: mobile_device_model
  type: STRING
  mode: NULLABLE
  description: Model name of the mobile device from session_start event
- name: mobile_device_string
  type: STRING
  mode: NULLABLE
  description: |-
    Branding, model, and marketing name identifying the mobile device from session_start event
- name: os
  type: STRING
  mode: NULLABLE
  description: "Operating system name (e.g., Macintosh, Windows) from session_start
    event"
- name: os_version
  type: STRING
  mode: NULLABLE
  description: "Version of the operating system from session_start event"
- name: language
  type: STRING
  mode: NULLABLE
  description: |-
    IETF language code of the device language setting from session_start event
- name: browser
  type: STRING
  mode: NULLABLE
  description: "Browser name (e.g., Chrome, Firefox) from session_start event"
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: "Version of the browser from session_start event"
- name: first_campaign_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null campaign value extracted from event_params across all
    session events, ordered by timestamp"
- name: distinct_campaigns_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique campaign values from event_params during the session"
- name: first_source_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null source value extracted from event_params across all
    session events, ordered by timestamp"
- name: distinct_sources_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique source values from event_params during the session"
- name: first_medium_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null medium value extracted from event_params across all
    session events, ordered by timestamp"
- name: distinct_mediums_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique medium values from event_params during the session"
- name: first_content_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null content value extracted from event_params across all
    session events, ordered by timestamp"
- name: distinct_contents_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique content values from event_params during the session"
- name: manual_campaign_id
  type: STRING
  mode: NULLABLE
  description: Campaign ID from collected_traffic_source at session_start event
- name: manual_campaign_name
  type: STRING
  mode: NULLABLE
  description: Campaign name from collected_traffic_source at session_start 
    event
- name: manual_source
  type: STRING
  mode: NULLABLE
  description: |-
    Traffic source from collected_traffic_source at session_start event
- name: manual_medium
  type: STRING
  mode: NULLABLE
  description: |-
    Traffic medium (e.g., organic, cpc, referral) from collected_traffic_source or utm_medium parameter at session_start
- name: manual_term
  type: STRING
  mode: NULLABLE
  description: Marketing term from collected_traffic_source at session_start 
    event
- name: manual_content
  type: STRING
  mode: NULLABLE
  description: Marketing content from collected_traffic_source at session_start 
    event
- name: gclid
  type: STRING
  mode: NULLABLE
  description: Last reported Google Click ID uniquely identifying an ad click 
    for Google Ads
- name: gclid_array
  type: STRING
  mode: REPEATED
  description: Array of all Google Click IDs reported during the session
- name: had_download_event
  type: BOOLEAN
  mode: NULLABLE
  description: "Boolean flag indicating if the session included any Firefox, Focus,
    or Klar download event"
- name: firefox_desktop_downloads
  type: INT64
  mode: NULLABLE
  description: "Count of Firefox desktop downloads (win, win64, macos, linux platforms)
    during the session"
- name: last_reported_install_target
  type: STRING
  mode: NULLABLE
  description: "Most recent install target reported (e.g., desktop_release, android_beta),
    based on latest download event timestamp"
- name: all_reported_install_targets
  type: STRING
  mode: REPEATED
  description: "Array of all install targets from download events during the session"
- name: last_reported_stub_session_id
  type: STRING
  mode: NULLABLE
  description: "Most recent stub session ID from stub_session_set events, joinable
    with dl_ga_triplets for dl_tokens"
- name: all_reported_stub_session_ids
  type: STRING
  mode: REPEATED
  description: "Array of all stub session IDs from stub_session_set events during
    the session"
- name: landing_screen
  type: STRING
  mode: NULLABLE
  description: "First reported page location (without query parameters) marked with
    entrance flag in the session"
- name: first_term_from_event_params
  type: STRING
  mode: NULLABLE
  description: "First non-null term value extracted from event_params across all session
    events, ordered by timestamp"
- name: distinct_terms_from_event_params
  type: STRING
  mode: REPEATED
  description: "Array of all unique term values from event_params during the session"
- name: ad_google_campaign
  type: STRING
  mode: NULLABLE
  description: Google Ads campaign name from session_traffic_source_last_click 
    at session_start event
- name: ad_google_campaign_id
  type: STRING
  mode: NULLABLE
  description: Google Ads campaign ID from session_traffic_source_last_click at 
    session_start event
- name: ad_google_group
  type: STRING
  mode: NULLABLE
  description: Google Ads ad group name from session_traffic_source_last_click 
    at session_start event
- name: ad_google_group_id
  type: STRING
  mode: NULLABLE
  description: Google Ads ad group ID from session_traffic_source_last_click at 
    session_start event
- name: ad_google_account
  type: STRING
  mode: NULLABLE
  description: Google Ads account name from session_traffic_source_last_click at
    session_start event
- name: ad_crosschannel_source
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign source from 
    session_traffic_source_last_click at session_start event
- name: ad_crosschannel_medium
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign medium from 
    session_traffic_source_last_click at session_start event
- name: ad_crosschannel_campaign
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign name from 
    session_traffic_source_last_click at session_start event
- name: ad_crosschannel_campaign_id
  type: STRING
  mode: NULLABLE
  description: Cross-channel campaign ID from session_traffic_source_last_click 
    at session_start event
- name: ad_crosschannel_source_platform
  type: STRING
  mode: NULLABLE
  description: Cross-channel source platform from 
    session_traffic_source_last_click at session_start event
- name: ad_crosschannel_primary_channel_group
  type: STRING
  mode: NULLABLE
  description: Cross-channel primary channel grouping from 
    session_traffic_source_last_click at session_start event
- name: ad_crosschannel_default_channel_group
  type: STRING
  mode: NULLABLE
  description: Cross-channel default channel grouping from 
    session_traffic_source_last_click at session_start event
- name: first_experiment_id_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null experiment ID extracted from event_params during 
    the session, ordered by timestamp
- name: distinct_experiment_ids_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique experiment IDs from event_params during the 
    session
- name: first_experiment_branch_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null experiment branch/variant extracted from 
    event_params during the session, ordered by timestamp
- name: distinct_experiment_branches_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique experiment branches from event_params during 
    the session
- name: first_gad_campaignid_from_event_params
  type: STRING
  mode: NULLABLE
  description: First non-null Google Ads campaign ID extracted from event_params
    during the session, ordered by timestamp
- name: distinct_gad_campaignid_from_event_params
  type: STRING
  mode: REPEATED
  description: Array of all unique Google Ads campaign IDs from event_params 
    during the session
