fields:
- name: as_of_date
  type: DATE
  mode: NULLABLE
  description: Date field
- name: country_code
  type: STRING
  mode: NULLABLE
  description: ISO country code
- name: total_rows
  type: INTEGER
  mode: NULLABLE
  description: Total count or sum
